### ISSUE TITLE
Fantastic journey gfx problems

### ISSUE THREAD

**Issue by kounabi22** [libretro/mame2003-plus-libretro#1641] opened 2023-10-18 06:47 UTC
Fantastic journey (Fantjour) have black screen in game menu but you can choose character and after game start it apear only some background layers and plays croppy sounds.

**Comment by arcadez2003** [comment] 2023-10-18 20:05
@kounabi22 https://github.com/libretro/mame2003-plus-libretro/commit/695df35cf60973228b85e7fc0764866265c10f6d

Try it out and lemmie know how it goes

**Comment by kounabi22** [comment] 2023-10-18 20:57
Ok i will try when retropie update the binary file cause i play on pi4.

**Comment by mahoneyt944** [comment] 2023-10-19 02:51
You would have to update mame2003-plus "from source" if you want to try this update sooner. The binaries aren't updated to often, though you may try requesting they do so. Idk if they would or not.

**Comment by mahoneyt944** [comment] 2023-10-19 16:38
Just tried this and I'm still getting a black screen after the rom check.

**Comment by kounabi22** [comment] 2023-10-19 20:19
yes try it, same problem.

**Comment by arcadez2003** [comment] 2023-10-19 22:36
> Just tried this and I'm still getting a black screen after the rom check.

Code is confirned to work on my xbox MAME84 test core i couldn't try the game using MAME72 due to running
out of mem on boot which is not ideal as i could not test the memory address values to make sure the game
will work with them.

However i'll check the code again to make sure i didn't miss anything but i strongly suspect this will be the cause......

				/* program_read_dword program_write_dword */ MAME84 
					cpu_writemem32bedw_dword(da, cpu_readmem32bedw_dword(sa) ^ x); /* correct for 78.?? */

Total guess with the above i'll need to look into to it a little deeper.

**Comment by arcadez2003** [comment] 2023-10-19 22:43
@mahoneyt944 

As you know this covers all bases /* program_read_dword program_write_dword */ MAME84 where as we have more
variables in 78 it's finding the correct one which is the problem try switching from 32 to 24 in WRITE32_HANDLER(fantjour_dma_w)

                                        cpu_writemem24bedw_dword(da, cpu_readmem24bedw_dword(sa) ^ x); /* correct for 78.?? */
and
					cpu_writemem32bedw_dword(da, x); /* correct.?? */

**Comment by mahoneyt944** [comment] 2023-10-20 00:15
Do you have the original commit link? I can try to convert that line and see if I get what you got.

**Comment by arcadez2003** [comment] 2023-10-20 08:08
https://github.com/arcadez2003/mame/commit/6422c02a91363e324f65768d8e7dbc1bd7fc6df7

**Comment by arcadez2003** [comment] 2023-10-20 15:17
Alright been looking over my 84 src not many program_read/write_dword calls seicop.c has quite a few and i remember
having to toggle a few of them around so that denjin makai would boot in this core, by looks from what i've compared

the dword calls are most likely to be as i had em for this commit cpu_writemem32bedw_dword cpu_readmem32bedw_dword
but i noticed the ones i had to change for denjin were cpu_readmem24bew_dword cpu_writemem24bew_dword.

It's worth a try to use the above to see if that sorts fantastic journey again im sorry for this hastle in an ideal world
this game would boot on the xbox without requiring a VMM routine and then i could have used MAME72 to find
the correct mem calls for the prot code.

**Comment by kounabi22** [comment] 2023-10-21 10:25
i update via source and the game works like a charm....ty.

**Comment by arcadez2003** [comment] 2023-10-21 12:51
Alright thanks @grant2258 i think we can close this down now yet another happy ending

**Closed by arcadez2003** 2023-10-21 12:51 UTC
