### ISSUE TITLE
Shift indicators

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1712] opened 2024-04-26 04:20 UTC
I removed the old debug shift indicator for polepos and polepos2 and redid it to draw down in the corner in the "spirit" of how newer mame uses overlays. Seems to achieve the same idea, with a slightly smaller footprint on the screen.
![poleposa-240426-105421](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/24ff654e-f3a8-4985-8502-400b6b2eabc9)

I also went ahead and added this same shift indicator for outrun and toutrun.
![outrun-240426-001114](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/73fba5af-3450-4062-be8f-04d26ba1a3ce)
![toutrun-240426-001222](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/211752ac-79f1-491e-a15d-b155ca6f22a8)

Any feedback is appreciated, thanks!

Also any other games that might need this indicator?

@KMFDManic , @arcadez2003 , @grant2258

**Comment by mahoneyt944** [comment] 2024-04-26 14:55
For reference here's polepos with the indicator in the lower left corner instead
![poleposa-240426-105421](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/24ff654e-f3a8-4985-8502-400b6b2eabc9)

**Comment by grant2258** [comment] 2024-04-27 17:22
Dont think the sides matter all others put it to the right for some reason even fbneo. Using a gfx stick isint an option unless you use a bigger frame buffer with scaling.

**Comment by mahoneyt944** [comment] 2024-04-27 17:25
@grant2258 I went to the left because it seemed to not cover any graphics for these games not sure it matters, maybe it could be an option?

**Comment by mahoneyt944** [comment] 2024-04-30 20:54
I fixed up wecleman and hotchase then added indicators to them. Wecleman is fun to play. Hotchase however plays slow, seems like it needs an overclock of 200% to play smooth... I'm thinking there's something out of time but haven't figured it out.

**Comment by mahoneyt944** [comment] 2024-05-03 03:34
@KMFDManic wecleman and hotchase might be good picks for your channel. Pretty fun and as mentioned hotchase benefits from an overclock (perfect for Xtreme).
![wecleman-240430-135700](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/8b137109-ae35-45d2-b992-31388b31232f)
![wecleman-240430-231315](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/5bd8b808-d21a-47d7-a740-c99fea2d7e1d)

**Comment by KMFDManic** [comment] 2024-05-03 04:29
@mahoneyt944 thanks for the amazing surprise pings.  I will check out these hot additions and integrate and showcase, as well as think of other games that would benefit from shifter:) Thanks again, as always! Tremendous racing game fan, as you were already aware:)

**Comment by mahoneyt944** [comment] 2024-05-04 17:42
@KMFDManic that would be awesome. With the fix for bowler (support for rotated font), it will also allow this shifter to work for vertical games. I'm probably just going to add support as I come across them or people request certain titles. I pretty much nailed the ones I'd personally use. So any suggestions would be great.

**Comment by markwkidd** [comment] 2024-05-04 17:50
It's amazing how you all keep enhancements like this coming. So cool.

**Comment by mahoneyt944** [comment] 2024-05-04 19:19
> It's amazing how you all keep enhancements like this coming. So cool.

Thanks Mark, glad to see you're still kicking around 😅.

**Comment by markwkidd** [comment] 2024-05-04 19:43
For sure, I enjoy popping into this repository regularly to see what's being committed.

I'm on my third year of operating the family farm in the mountains, my schedule is still too full for much coding. But I've gotten involved in an open-source vegetable breeding community, I enjoy that in some of the same ways. 

Cheers again! 👍 🌱

**Comment by mahoneyt944** [comment] 2024-05-06 08:13
And another
![topspeed-240506-040548](https://github.com/libretro/mame2003-plus-libretro/assets/49591133/58f8ecf5-b094-40e5-bfd4-3e11e320576a)

**Comment by KMFDManic** [comment] 2024-05-06 15:15
@mahoneyt944 I'd say the best way to handle this would be curate a list of "racing" and other potential games that can benefit from this very creative and kickass addition.  I, personally, have always been a bit annoyed when playing OutRun...almost having to pay attention to the "gear shifting" to truly feel and know if I was in Hi or Lo.  With that being said, if we have a decent curated list, I can personally test all on the list, and quickly ascertain which are clearcut and which truly need a little "visual" boost.

When checking a list of Racing Games for MAME in general, to my surprise, I came across one that "we likely cannot play", called Thrill Drive.  It seems to work on MAME 147, but not really other MAMEs.  It feels like an earlier incarnation of one of the "crazy drive in traffic" mode of the various Burnout titles.  It definitely piques my interest enough to try it out and see if I can get it playable somehow.  It may only work on MAME 2014-2015, if at all.  I absolutely love obscure racing games!

Speaking of which, if you are as much a racing game fan as me, two obscure racers I very much love are RC De Go! (similar to RC ProAm) and N-Gen Racing for PS1! (Gran Turismo with Planes).

I am definitely onboard with anything related to Racing Games.  If we can get a list of MAME Racers, we can quickly see what is useful within the context of MAME 2003, and go from there.  I can get a video up on my next day off, showcasing before and after examples of some of these.  Thanks again:)!

I am sure there are other racers neither of us are aware of, as well!  Thrill Drive was certainly a pleasant surprise gem to come across.  So, hoping I can get it working somehow:)  I know, for sure, you'd need to reset the game to have NVRAM initialize, like with Robotron, etc, at least in my initial testing on MAME 2015.  Would be beautiful if something like this could even feasibly work in 2003!!!

**Comment by markwkidd** [comment] 2024-05-06 15:43
Could catver.ini be useful for this? `Driving` is the tag I would suggest using as a reference?

**Comment by mahoneyt944** [comment] 2024-05-06 20:40
> Could catver.ini be useful for this? `Driving` is the tag I would suggest using as a reference.

Yes, however some games have built in indicators so you really have to test each one. A better option might be to reference current mame's overlays for gear shifters. Haven't looked at it myself but likely some tags to follow in there.

**Comment by KMFDManic** [comment] 2024-05-08 16:44
@mahoneyt944 Did a preliminary test.  It is definitely the kind of addition that really enhances the gameplay in games where you have to put guesswork into if you are in hi or lo gear.  We really need to find a fairly reasonable way to verify what games have hi and lo gears.  One thing later MAME added, was an overlay for OutRun, etc.  Rather than it just say hi/lo, you can actually see a slicker presentation, such as in the overlay files I am dropping here.
[outrun_overlay.zip](https://github.com/libretro/mame2003-plus-libretro/files/15252073/outrun_overlay.zip)

Imagine a scenario, where tapping hi/lo gear would be able to swap between those overlays (the hi/lo ones)..Damn, that would be cool as hell.  Even a mock gear shift:)  Creativity knows no bounds, when it comes to MAME 2003 Plus:)

For now, I have a few fun games to showcase.  But, it would be badass, if we could incorporate some sort of on the fly overlay swapping that is tethered to the hi lo gear shift.  That is something I bet @grant2258 would really enjoy, too, hehe:)

**Comment by mahoneyt944** [comment] 2024-05-08 20:31
As grant noted above, we'd need a bigger frame buffer and scaling...and I believe the core has to export some general information about the Input to work with the overlay. So it's not an easy addition to use overlays, hence this solution here.

**Comment by KMFDManic** [comment] 2024-05-08 21:35
@mahoneyt944 sorry, I must have missed that comment.  Rereading the thread:) So far so good, otherwise, however.  The games that dont display hi or lo are infinitely more playable.  Just need to sort out any others that may suffer this pratfall.

**Comment by grant2258** [comment] 2024-05-08 22:11
The scaling will happen if we increase the frame buffer. If you start mame current on libretro you can see how bad the gear stick, it looks fine 640x480 or 800x600 would be ideal. That in itself isint the real issue though sharers act all funny with higher resolutions. 

I think you can adjust the settings for them not something ive looked into to be honest. One game that will display the issue is kick as it has a high resolution the screen will appear to bounce. Just load crt geom with kick and youll see what I mean. It could  be done as core option easily enough though. Im pretty sure there would be complaints maybe as the libretro folk about shades and bigger framebuffers.

**Comment by KMFDManic** [comment] 2024-05-08 22:55
@grant2258 and that is why I dont mind xtreme being the guinea pig in intial cases like this, hehe.

**Comment by grant2258** [comment] 2024-05-10 16:56
It can be done but would need workarounds that arent worth the effort. It would be nice if RA allowed a core to insert an overlay as you cant even get the the current its using. Scaling with mame then scaling RA scaling to it view port would hurt low end devices. I dont know any way around this apart from implementing a vulkan  for plus as gl has too many overheads

**Comment by KMFDManic** [comment] 2024-05-10 17:44
@grant2258 not a huge deal, then, if it truly is that much of a hassle.  Im happy enough for now just being able to know which gear it is in, rather than guess:)  Just need to do more research and testing to see what other racers may benefit this phenomenal addition.

**Comment by grant2258** [comment] 2024-05-10 19:38
There might be other ways around this first thought is adding artwork support thats interactive with  an input port status.

**Comment by mahoneyt944** [comment] 2024-05-11 00:04
> @grant2258 not a huge deal, then, if it truly is that much of a hassle. Im happy enough for now just being able to know which gear it is in, rather than guess:) Just need to do more research and testing to see what other racers may benefit this phenomenal addition.

Should be pretty easy to add more games. Just let me know if there's any you come across.

**Closed** 2024-05-17 15:46 UTC
