### ISSUE TITLE
Possible psikyosh improvements?

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-plus-libretro#910] opened 2020-10-30 00:57 UTC
There's one in particular that's benefiting one particular game:

0.99u5: David Haywood added blending to the alt tilemap code in PsikyoSH driver, fixing the final boss in Sol Divide.

There's another that may be impactful towards improving speed:

0.154: Hook up fastram to PsikyoSH driver, (s1945ii 900%->1700%) [R. Belmont].

**Comment by arcadez2003** [comment] 2020-10-30 13:57
I knew about the first fix for Sol Divide, the problem is this core is aimed at low spec devices and if i was to
backport the alpha blending video changes then the performance in all the psikyosh games will drop as
a result.

As for the other commit fastram is connected to the SH2 core i looked into this a while back but the code in
question is not compatible with this core as far as i can tell, i'll take a peek at it again sometime

**Comment by arcadez2003** [comment] 2020-11-12 00:55
Closing as we cant use code that will hurt game performance, and the fastram from the latest SH2 CPU cores
is not compatible with our codebase.

**Closed by arcadez2003** 2020-11-12 00:55 UTC
