### ISSUE TITLE
B.Rap Boys (brapboys.zip)

### ISSUE THREAD

**Issue by Loggahead** [libretro/mame2003-plus-libretro#206] opened 2018-05-17 12:16 UTC
Request to get B.Rap Boys working in 2003plus. It just crashes back to ES when you try and launch it.  I currently have it working in mame2010.

**Comment by arcadez** [comment] 2018-05-17 13:01
I've had conflicting reports with this game some folks said it works but has graphical
problems where as others said it it was fine apart from some sound issues here and
there.

i'll look into this sometime as i suspect some of the cpu decryption code in the updated
Kaneko16 driver is wrong for this core unless someone else fancies running it by a debugger

**Comment by ZappaUtopia** [comment] 2018-05-17 13:40
You need to turn off 'Rewind' in RetroArch.

**Comment by Loggahead** [comment] 2018-05-17 13:43
I've looked for 'Rewind' but couldn't find the option.  Where in the world is it?  I checked the Select+X menu but didn't see it there.  I'll test it again once I make sure that is disabled and report back.

**Comment by ZappaUtopia** [comment] 2018-05-17 13:48
It's in `Settings —> Frame Throttle —> Rewind`.

@arcadez A while ago I also reported that this game had a buzzing sound, that's now gone !

**Comment by Loggahead** [comment] 2018-05-17 17:01
Sounds good.  I'll do that tonight.  That's something I'll need to disable in my global retroarch.cfg right?

**Comment by Loggahead** [comment] 2018-05-18 11:48
Checked my rewind option and it was already disabled.  :(  I don't think BRap boys needs a bios does it?  Its running fine in 2010 without one.  

Ah well, must be something on my end if you can confirm it works with 2003+ on your end.  Note that I am running rpie 4.4 on an pi3b

**Comment by grant2258** [comment] 2018-05-18 12:41
brapboys.zip shogwarr.zip not working mr loggahead

**Comment by ZappaUtopia** [comment] 2018-05-18 16:10
I have just built from source and `brapboys` and `shogwarr` work fine. Those two games were part of the 'dont work when rewind is on' category.

**Comment by grant2258** [comment] 2018-05-18 16:13
@arcadez  must have fix it was segfaulting thats good news

**Comment by grant2258** [comment] 2018-05-18 18:44
hmm its working on 64 bit as well dont know what changes since last time @arcadez but its working now

**Comment by ZappaUtopia** [comment] 2018-05-18 19:03
The game has always worked but doesn't when 'Rewind' is switched on.

**Comment by grant2258** [comment] 2018-05-18 19:04
]=0@no i was getting different segfaults for that one @ZappaUtopia

**Comment by Loggahead** [comment] 2018-05-18 21:35
I'm confirming that I had and still have rewind turned off in retroarch and it wasn't working for me either.  I'll update source and try again.

**Comment by arcadez** [comment] 2018-05-18 22:16
ok then good news all round i'll close this now

**Closed by arcadez** 2018-05-18 22:16 UTC

**Comment by markwkidd** [comment] 2018-05-18 22:36
@Loggahead  is this confirmed **working** or confirmed **not working**
