### ISSUE TITLE
Title fight - right screen missing some sounds

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1876] opened 2024-11-08 15:56 UTC
While testing I noticed there's missing sounds for the right screen but not the left, such as:

- part of "ladies and gentlemen Sega presents the main event"
- ending credits music
- character select music
- next opponent sounds
- rematch count down sounds
- countdown starts with 2 - 1 - 2 - 3

**Comment by arcadez2003** [comment] 2024-11-08 16:03
One or two bug reports regarding missing voices and or sounds i dunno if you've read em...
https://mametesters.org/view_all_bug_page.php?filter=132399

**Comment by mahoneyt944** [comment] 2024-11-08 16:07
Yeah I've seen those. Idk if it's related to the missing engine sounds of scross or not but it could also be our sound map or sound core.

**Comment by arcadez2003** [comment] 2024-11-09 00:03
@mahoneyt944 
[Try this.zip](https://github.com/user-attachments/files/17685248/Try.this.zip)

**Comment by mahoneyt944** [comment] 2024-11-09 00:30
> @mahoneyt944 [Try this.zip](https://github.com/user-attachments/files/17685248/Try.this.zip)

No luck

**Comment by grant2258** [comment] 2024-11-09 01:53
The count starts with countdown 1 2 3 ..  here im not it could be android specific is fine on the pc and raspberry pi5. For the right screen its an easy one to over look you only have one set of ym and multipcm you need two of each if you want the second side to have sound and hook it up of course. There is also a problem with a+b screen select its just black. I don't really use these settings anyway just to let you know.

**Comment by grant2258** [comment] 2024-11-09 04:50
On closer inspection of the mame code system32 is using 2 ym but multi32 is just using one. It looks like the port map is missing some interrupt handling.

https://github.com/grant2258/mame/blob/4da96a0c4fbc9ee692082e889b3a5a913fc0659e/src/mame/sega/segas32.cpp#L1243

**Comment by mahoneyt944** [comment] 2024-11-09 14:09
> There is also a problem with a+b screen select its just black.

Are you using the latest commit? If so what's the setup to recreate this?

**Comment by mahoneyt944** [comment] 2024-11-09 14:14
> On closer inspection of the mame code system32 is using 2 ym but multi32 is just using one. It looks like the port map is missing some interrupt handling.
> 
> https://github.com/grant2258/mame/blob/4da96a0c4fbc9ee692082e889b3a5a913fc0659e/src/mame/sega/segas32.cpp#L1243

We are using that hookup. What's missing?
https://github.com/libretro/mame2003-plus-libretro/blob/9965d14d88f0e04b3cdbe8433093e4152fc42f11/src/drivers/segas32.c#L1119

**Comment by grant2258** [comment] 2024-11-09 14:53
@mahoneyt944 there are some mirrors in that map sorry if that wasnt clear what I was saying. You can check you logs for and unmapped port read writes if there are none it wont be a issue. I could well be the the re trigger bug but its worth checking any unmapped read writes.

**Comment by mahoneyt944** [comment] 2024-11-09 15:02
> I am at the latest commit btw.

And you're getting black outs on the A+B selection? I can't replicate that. I toggle it like crazy and it always displays correctly for me.

**Comment by grant2258** [comment] 2024-11-09 16:10
Yes its happening on the pc and raspberry pi5 with titlef because I wanted both screens on.  ill test with another game orunners, hard drunk and scross are doing the same thing. The A B alone works fine. Try this set the dipswitch to ab and restart the game. The display is so far off where it should be you cant even bring up the gui.

**Comment by mahoneyt944** [comment] 2024-11-09 16:15
> Try this set the dipswitch to ab and restart the game. The display is so far off where it should be you cant even bring up the gui.

Works fine for me.

**Comment by grant2258** [comment] 2024-11-09 16:26
yea i am https://github.com/libretro/mame2003-plus-libretro/commit/6009a8ed48837b5e14db10acdbc5b28d3c0f20e2 is where it broke I just reverted back till iot worked.

**Comment by mahoneyt944** [comment] 2024-11-09 16:59
I don't see how that would effect anything, the visible area is updated on every video update based on the dip selection?  I'm launching from the gui on the current commit without any issue no matter if I toggle the dip or reset.

**Comment by grant2258** [comment] 2024-11-09 17:36
not sure whats going to be honest your setting up the screen bitmap as MDRV_SCREEN_SIZE(52*8*2, 28*8) which is fine size wise. And the clips set to MDRV_VISIBLE_AREA(0*8, 52*8-1, 0*8, 28*8-1)

the difference is the max size is 416x416 which is correct for  52*8 the mystery really is why the RA max size is 832 when launched from retroarch and 416 when launched from command line which is the information mame is giving

**Comment by mahoneyt944** [comment] 2024-11-09 17:41
It seems like launching from command line is riddled with odd bugs. Likely devs have not tested this against the behavior from Ra directly

**Comment by grant2258** [comment] 2024-11-09 17:53
Its not an odd bug its an odd bug it works MDRV_VISIBLE_AREA(0*8, 52*8-1, 0*8, 28*8-1) = 416 * 224 video code reads the visible area here. https://github.com/libretro/mame2003-plus-libretro/blob/9965d14d88f0e04b3cdbe8433093e4152fc42f11/src/mame2003/video.c#L68 unless you at some point are updating the visible area which I havent checked its a miracle its getting changed at all.

**Comment by mahoneyt944** [comment] 2024-11-09 18:04
> unless you at some point are updating the visible area which I havent checked its a miracle its getting changed at all.

Yes every video update
https://github.com/libretro/mame2003-plus-libretro/blob/9965d14d88f0e04b3cdbe8433093e4152fc42f11/src/vidhrdw/segas32.c#L2743-L2772

**Comment by grant2258** [comment] 2024-11-09 18:13
this is strange the max setting in the geometry is 416 from the command  or retroarch 832 will need to hunt down where its tripping

**Comment by mahoneyt944** [comment] 2024-11-09 18:18
> this is strange the max setting in the geometry is 416 from the command or retroarch 832 will need to hunt down where its tripping

That is odd. Maybe command skips some function call from Ra? Or skips the video update on init

**Comment by mahoneyt944** [comment] 2024-11-09 19:22
We could add `*2` back into the driver start if that solves the command issue?

**Comment by grant2258** [comment] 2024-11-09 19:34
looked this up checked the latest libretro.h its description is changed from ours. The initial config sticking makes sense no idea why its acting differently from command line though. 

https://github.com/libretro/RetroArch/blob/876cc19d49e241dfaa2eb794f2544e7ae70d9858/libretro-common/include/libretro.h#L1323-L1359

Seems to make sense might be a change in behavior since the video code was done years ago.

**Comment by mahoneyt944** [comment] 2024-11-09 19:41
We default the dips to monitor A, which is why the visible area is set to one screen in the driver, but regardless it should behave the same way since it updates it in the video update every call. Is this a core bug or Ra bug?

**Comment by grant2258** [comment] 2024-11-09 20:02
its not a bug read the description again we use RETRO_ENVIRONMENT_SET_GEOMETRY.

The very first setting with the visible area is  max 416 x  224  now. So anything bigger would require a RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO change due to the visible area change being bigger than what it was initialized with. That change just lowered the max area it probably should be fixed properly for any edge cases.

**Comment by mahoneyt944** [comment] 2024-11-09 21:03
I just assumed it would init that based on MDRV_SCREEN_SIZE, I pushed the *2 back in though.

**Comment by mahoneyt944** [comment] 2024-11-10 02:48
@grant2258 hey, see if this branch fixes loading from command line, it doesn't seem like we init the video_config size properly. This might solve the issue https://github.com/libretro/mame2003-plus-libretro/compare/master...Size

**Comment by grant2258** [comment] 2024-11-10 05:25
> @grant2258 hey, see if this fixes loading from command line.
already answered here https://github.com/libretro/mame2003-plus-libretro/issues/1876#issuecomment-2466275257

https://github.com/libretro/mame2003-plus-libretro/issues/1876#issuecomment-2466421952 explains the issue the video code is fine and does what it should be doing. Its not setting it wrong its RA that is not handling the resolution changes properly due to the geometry call limitation when the resolution is bigger than the original RA max set,  RA has a mechanism if the resolution gets larger though  that would be the optimal solution for lower end hardware. 

The solution will work the only problem is the screen size is often bigger than the visual display its not ideal for low end hardware using extra memory when not needed. If your happy using the extra memory always it will work. I would personally use a solution that used as little memory as possible due to some of the platforms people use this core on. I don't personally use the core as such but its down to yourself what way you want to do it all roads lead to Rome.

**Comment by grant2258** [comment] 2024-11-10 07:00
The solution is like it should be you set it to what is required not what its possible to change too. Both work at the end of the day. You should really change the geometry in retro_run that the api spec mentions this it might play nice in other front ends even in RA there is difference from the command line and launching from ra itself.

**Comment by mahoneyt944** [comment] 2024-11-10 07:41
Well I can revert that last commit if you think it's better that way. As far as calling it in retro_run(), we do technically, its just buried deep within mame_frame().....It would be called before retro_run() completes when there's a geometry change. I can ask if that meets the API's requirements if that's in question.

**Comment by mahoneyt944** [comment] 2024-11-10 14:13
Also if we are worried about the Max and the memory size that comes with it, horizonal games (non - Tate) should probably sets the width and height independently since they won't be rotating. Right now we just set both to which ever is highest.

**Comment by grant2258** [comment] 2024-11-10 18:52
@mahoneyt944 its the libretto api that says this not me. I can tell you using RETRO_ENVIRONMENT_SET_SYSTEM_AV_INFO  in the main code in the past (which we dont use) caused crashes sometimes unless you called it at in retro_run itself. You have to member mame is rendering the next frame not the current one its draws the one made in the last frame. 

You can implement it anyway you see fit. mameframe does many things it runs the iteration required if you can guarantee the order and the time of main loop, who am I to debate the common sense approach libretro takes by says call it in retro run so there isint any issues in any front ends and its guaranteed to be called in a timely fashion. Im only discussing this not asking you to change anything. It was only the inconsistent launch from the command line and from RA itself that I thought needed to be looked into and at least the reason was found in this case. This isint the first time we came across this the other time its was something else cant even remember what it was that didn't launch properly from the command line I never looked into it then.  

If you want to patch the max up like you did go for it. I just like keeping memory and things as low as possible in an ideal world.

**Comment by mahoneyt944** [comment] 2024-11-10 18:57
As long as the `*2` fixes the command line issue, I'm indifferent about it. I'll leave it be.

**Comment by grant2258** [comment] 2024-11-10 19:01
It would probably be best to check in mame you can turn the sound up and down to see what chip makes what sounds. If its the multipcm it could well be the re trigger. I would defo check for any unmapped mirrors in the port reads I think there was 2 mirrors in there.

**Comment by mahoneyt944** [comment] 2024-11-10 19:04
Did the pre-segas32 driver have the same issue? That might tell us something too.

**Comment by grant2258** [comment] 2024-11-10 19:13
Tried it on my test core seems to have the second player sounds missing not sure about this core though. I would imagine the drivers where around the same state since its only mame095

**Comment by mahoneyt944** [comment] 2024-11-10 20:07
Hmm. It's probably the same bug as the missing sounds  in across. Not sure how difficult it would be to implement that

**Comment by arcadez2003** [comment] 2024-11-10 22:21
Maybe this but dunno how much work it would be just get it ported so you can test the games..
0.231: Retrigger after writing to sample register if key is on (YMF278 also does this) (sound\multipcm.cpp). Fixes no engine sound in Stadium Cross and clones [dink, hap].

**Comment by grant2258** [comment] 2024-11-11 00:19
@arcadez2003 it works with the other banking just tried it.

**Comment by grant2258** [comment] 2024-11-11 03:57
ive added the updates to my test core in case there is any other gremlins that can arrise

**Comment by mahoneyt944** [comment] 2024-11-11 04:25
@arcadez2003 you're the man! Nice find. Sound working now. Curious is the sound broken in current mame?

**Closed** 2024-11-11 09:05 UTC

**Comment by mahoneyt944** [comment] 2024-11-11 11:12
@grant2258 @arcadez2003 so I looked into the missing engine sounds in scross, using dinks commit https://github.com/finalburnneo/FBNeo/commit/a565a5d6dc362398362f363091abd5e12cbf980e I was able to get it working in this core https://github.com/libretro/mame2003-plus-libretro/compare/master...Fix 

I'm not entirely sure this port is 100% correct, but it's working. Either of you see anything out of order on this branch. Might need some help testing effected games if it looks good to you guys.

**Comment by arcadez2003** [comment] 2024-11-11 23:38
Code seems correct it's chalk and cheese isn't it FBN vs MAME2003+ it's good there's not that many
games affected as we can test em a bit a time in short order, as for current MAME i dont know if
Title Fight has sound issues you'd need to test it.

But they'd never accept a fix from us anyhow as we're the bad guys :)

**Comment by arcadez2003** [comment] 2024-11-11 23:45
> @arcadez2003 you're the man! Nice find. Sound working now. Curious is the sound broken in current mame?

Well im the man that likes to guess :) i thought two screens problem with the sound on the second 
and then spotted scross has different handling as it's mono for both screens then thought maybe 
Title Fight is the same.

Anyway another happy ending what with the gfx and the sound sorted nice game this one i like it
so happy to see this.

**Comment by mahoneyt944** [comment] 2024-11-12 04:02
Yeah the oversight is in current mame and fbneo, I let dink know about it in case they want to sort it. But at least the sound and gfx seem to be correct for us and I'm happy with that 👍

**Comment by arcadez2003** [comment] 2024-11-12 12:09
If they dont accept it then that's the way it goes...
https://github.com/mamedev/mame/pull/12967

**Comment by mahoneyt944** [comment] 2024-11-12 12:23
> If they dont accept it then that's the way it goes... [mamedev/mame#12967](https://github.com/mamedev/mame/pull/12967)

😂 Good luck.

**Comment by grant2258** [comment] 2024-11-12 13:22
> If they dont accept it then that's the way it goes...
> [mamedev/mame#12967](https://github.com/mamedev/mame/pull/12967)

It works fine in mame, did any of you test it?

**Comment by mahoneyt944** [comment] 2024-11-12 13:55
I tried fbneo and noticed "Sega presents the main event" is cut off. Current mame seems to work though on the multi32 banking. Curiously, current mame uses a similar solution as dinks to fix missing engine sounds in scross but has a the retrigger twice. Maybe this allows the original banking to work? @grant2258 can you test if removing the the alternate banking for scross still allows scross to have sound in current mame? Maybe the double retrigger eliminates the need to change the banking?

**Comment by grant2258** [comment] 2024-11-12 15:51
@mahoneyt944 I dont have mame compiled right now only do it on released but ill check it on the next release. I could be updates to the sound driver itself that fixed it though. There was some over sized roms on scross you might want to fix them. Forgot to mention it done it when I ported to my test core. https://github.com/mamedev/mame/commit/f5ab78727a35e96374292a6e1fdf62b94ac7ee8e

**Comment by grant2258** [comment] 2024-11-12 16:06
Both sides work fine on my port with them roms and not using the alt banking on my port. changes not sure about here pretty sure we about the same code wise though.

**Comment by mahoneyt944** [comment] 2024-11-12 16:35
Well that's confusing. Right now everything works in mame2003+. Being that newer mame and fbneo have different results all using different sound cores and possibly rom changes, I'm not sure what to think. I'm not sure the commit arcadez made in current mame is correct or not now?

**Comment by grant2258** [comment] 2024-11-12 17:21
Could be the mirrors just letting you know you should remove the center panning though. It should be stereo for the multipcm interfaces.

**Comment by mahoneyt944** [comment] 2024-11-12 18:24
So probably need to revert the current mame commit then. Think it's worth updating the multipcm here or leave well enough alone? Not many games use it anyhow in this core.

**Comment by mahoneyt944** [comment] 2024-11-13 10:58
Tried it for the heck of it, still needs the scross_bank_w for titlef https://github.com/libretro/mame2003-plus-libretro/commit/59329d99c2e8edef43d1943eff9d57b769f9887c

**Comment by grant2258** [comment] 2024-11-13 19:54
@mahoneyt944 youll need to review the rom load and add the offsets to cpu2 mame eventually took the banking away as such in mame 0194 its up to you what version of the banking you want to use but it must match your rom loads.

**Comment by mahoneyt944** [comment] 2024-11-13 20:23
Yeah they removed `0x100000` from the region size and re-racked the rom loads and still use the region pointer and `0x2000` which is what we did here as well. Whatever reason titlef is working with scross banking is a mystery to me. I'm still thinking it's the mirrors or something.
https://github.com/mamedev/mame/blob/ca721f71f21a251e3da2a29d1ae85eb8ec0349e8/src/mame/sega/segas32.cpp#L5438

**Comment by grant2258** [comment] 2024-11-13 21:08
agreed  the offsets should work out something else is fishy you have cpu_setbank in the init and the sound isint using banks maybe its left overs? What code base is this at for the driver?

**Comment by mahoneyt944** [comment] 2024-11-13 21:12
It's aimed towards current mame, but with all the alterations on the input side it doesn't look much like it.

And cpu_setbank is used to set a bank pointer here
https://github.com/libretro/mame2003-plus-libretro/blob/627eb92a58270e14eb8f67c8878ba0aa587ea9e2/src/drivers/segas32.c#L1075

**Comment by grant2258** [comment] 2024-11-13 21:35
The problem is my test core isint even writing a multipcm_bank_w  at the point where players put credits in. This core is writing left:180000 right:100000 on boot. Probably interrupt related would need to look into that.

**Comment by mahoneyt944** [comment] 2024-11-13 21:59
Hmm. In this core all the multi32 have attract sound switched off in the service menu, not sure what other cores do but that maybe a difference

**Comment by grant2258** [comment] 2024-11-13 22:16
You can get odd results if you dont disable unsed ports they can do off things if there are any unused port dips change them to IPT_UNKNOWN save you having to look up the unused are active IP_ACTIVE_LOW or high. We really should and the macro to save porting time.

**Comment by mahoneyt944** [comment] 2024-11-13 22:49
The driver does use IPT_UNUSED in a few places, but not in the titlef inportports 
https://github.com/libretro/mame2003-plus-libretro/blob/627eb92a58270e14eb8f67c8878ba0aa587ea9e2/src/drivers/segas32.c#L2228

Anywho, I need to get some sleep before work. Let me know if you figure anything out with titlef using the alternate banking

**Comment by grant2258** [comment] 2024-11-13 23:09
Dear lord no wonder its not logging the driver init is calling scross

**Comment by arcadez2003** [comment] 2024-11-13 23:53
So i assume we need this set....

	struct MultiPCM_t *mpcm = sndti_token(SOUND_MULTIPCM, which);

As per other sound cores we'd need it like this for our core..

	struct MultiPCM_t *mpcm = &MultiPCM[which];

**Comment by mahoneyt944** [comment] 2024-11-14 05:35
This core uses `mpcm[]` as a global static struct and references it directly throughout the code where as the later versions change to pointer referencing on the fly. I don't think it will make much of a difference, but if we change to that, we'd have to properly allocate the space the pointers reference. Not over bearing since it's a relatively small core, but a little extra graft to fit to our C standards.

**Comment by mahoneyt944** [comment] 2024-11-14 05:44
Fwiw, titlef plays and sounds great with the scross banking here, why it's needed I'm not sure...I still think the mirrors have a roll it that, but if it works it works and probably not worth digging too deep.

**Comment by arcadez2003** [comment] 2024-11-18 23:47
> Fwiw, titlef plays and sounds great with the scross banking here, why it's needed I'm not sure...I still think the mirrors have a roll in that, but if it works it works and probably not worth digging too deep
> 
> @arcadez2003 you might want to revert that commit in current mame though as I suspect it may not be needed there and may have actually broke sound on the right screen. Damned if you do, damned if you don't...but at least it was with good intensions.

The commit has been reverted now so Title Fight is as it was in current MAME.
