### ISSUE TITLE
Gauntlet service mode glitch

### ISSUE THREAD

**Issue by WindyWinston** [libretro/mame2003-plus-libretro#808] opened 2020-05-26 16:45 UTC
@arcadez2003 Have you heard anything about this in your MAME history ? I'm using Gauntlet 2 Player `gaunt2p`. On level 1, if you collect the two keys and warp to level 8 it takes you to level 8. But if you enter service mode (and don't even change any options) and exit back to game, collect the two keys and go to the level 8 warp it takes you back to level 1 !? I had to delete all the gaunt2p configs to get it to correct itself. I'm not sure if it does this on other versions of Gauntlet.

EDIT: I just tried this on the parent `gauntlet` and it does the same thing. Entering the service menu screws the game.

**Comment by arcadez2003** [comment] 2020-05-26 20:42
Never bumped into this before, then again i've never entered the service mode and then started a
game afterwards, this sounds like a fault on the original arcade machine rather than an emulation
bug per say, i wonder if it does the same thing in latest MAME or FBN.

**Comment by WindyWinston** [comment] 2020-05-26 22:32
I suppose it could be a bug with this version number `rev 6`. Current MAME has `Gauntlet rev 14`.

**Comment by arcadez2003** [comment] 2020-05-26 22:54
ye they dumped loads more versions and renamed all the romsets a while back, best thing to do
is try another version of the games which we support in MAME2003+ and see if you get the same
issues.

Barring that just stay clear of the service mode ha ha.

**Comment by arcadez2003** [comment] 2020-05-26 23:00
This reminds me there is a game i cant mind the name just now but in any emulator if you press
any buttons while it's booting up the game will lock into service mode, it'll only start up and play
correctly if nothing is pressed till the title screen appears.

It was one of the issues on here a while back, i guess what im saying is your always gonna get quirks in emulation at least with the gauntlet games it's minor stuff, however i usually do an ingame reset
coming outta the service mode as i've usually changed a setting and want it to stick afterwards
maybe the gauntlet games expect a similar reset when exiting the service mode.??

**Comment by WindyWinston** [comment] 2020-05-26 23:02
Commando ?

I'll give the reset a try tomorrow.

**Comment by arcadez2003** [comment] 2020-05-26 23:03
Aye that was it

**Comment by WindyWinston** [comment] 2020-05-26 23:08
Actually, I think the 2 player version of Gauntlet is still rev 6 in current MAME. I'll check the reset though tomorrow and maybe MAME2010.

**Comment by dinkc64** [comment] 2020-05-26 23:31
I wonder if it has something to do with the old slapstic emulation?  A few bugs in gauntlet were caused by the older slapstic emulation.  I know in older versions of mame it's impossible to go past level 25 or 28 (my memory is shit, but it's something around that level#).

best regards,
- dink

**Comment by WindyWinston** [comment] 2020-05-27 09:36
So I tried it on `lr-mame2003` and `lr-mame2003plus` and they both have the warp glitch after entering service mode. What's interesting is that I also tried the original MAME32 v0.78 on Windows using the same rom and the glitch doesn't happen. Must be a libretro goof.

**Comment by WindyWinston** [comment] 2020-05-27 09:54
I tried something else. After the glitch has happened (it stays like that), I started deleting the `.cfg`, `.hi` and `.nv` files one by one to see what was affecting it. It seems to be the hiscore file !

Just out of interest, why does it save a hiscore file (on all games?) even when you haven't entered a hiscore ? MAME 0.78 doesn't do this.

**Comment by dinkc64** [comment] 2020-05-27 13:06
The emulator has no idea if you entered a hi score or not, it just emulates the game and saves/loads the chunk of memory where the hiscores are located.

**Comment by WindyWinston** [comment] 2020-05-27 13:32
Yeah, but MAME32 0.78 doesn't save a `.hi` file until you enter a hiscore. Don't know why the .hi file on lr-mame2003 glitches Gauntlet though.

**Comment by arcadez2003** [comment] 2020-05-27 13:43
@dinkc64 Thanks for your input, i guess we can put this down to another of those libretro emulation bugs as this issue is not present when using the standalone MAME78 core, i'll 
certainly look into the slapstick emulation sometime to see if there are some fixes which can be backported so the Gauntlet games dont get hung up on later levels.

Although im wary of doing a full rewrite as so many games would be affected and lots of testing
required afterwards.

**Comment by mahoneyt944** [comment] 2020-09-01 08:25
The .hi file is effecting this because it's loading the last played level saved in the .hi file. As noted here:
https://github.com/libretro/mame2003-plus-libretro/blob/3e33bd47586634cf6700dac732c9e7a8982e7269/metadata/hiscore.dat#L10331
I'm not sure the service menu is at all related. Delete the .hi file then load the game and get the keys to warp and it should work. Once you exit the game a .hi file is made saving this level which is loaded the next time you launch the game creating the glitch. I have not tested this but I believe this is what's going on here. The address used in the dat probably needs fixed to not include the level.

**Comment by WindyWinston** [comment] 2020-09-01 10:00
The service mode must be glitching the hiscore file.

If you collect the two keys and warp to level 8 it correctly loads level 8.

If you turn service mode on then off (don't even change any settings and don't reset the game), the level 8 warp takes you back to level one, even though the game says it's level 8.

If you delete the hiscore file then the warp works correctly (and any changed settings work) but if you goto service mode again, the glitch is back.

As I say, this doesn't happen on MAME32 0.78. It only saves a hiscore file when you enter a hiscore, whereas Libretro Mame saves a hiscore file even if you just enter and exit a game.

We'll just have to remember that if you change any settings in the service mode of this game, you'll have to delete the hiscore file afterwards before playing :)

**Comment by mahoneyt944** [comment] 2020-09-01 10:06
Test this:
1. delete the .hi file
2. Load the game to the attract screen (don't open the service menu).
3. Exit the game.
4. Relaunch the game any try to warp (don't enter the service menu).

Does the glitch still occur?

**Comment by WindyWinston** [comment] 2020-09-01 10:24
It works fine if you don't enter the service mode.

**Comment by mahoneyt944** [comment] 2020-09-01 10:26
> It works fine if you don't enter the service mode.

Tested with the conditions I posted above?

**Comment by WindyWinston** [comment] 2020-09-01 10:31
Yep, I deleted the hiscore file, loaded the game until it showed the attract demo, closed content. Then reloaded the game and collected the two keys to warp to level 8. It works fine.

As soon as you touch the service mode the game has the glitch and won't go away until you delete the hiscore file.

**Comment by mahoneyt944** [comment] 2020-09-01 10:33
Ok thank you. I'll check what difference there are in the memory. And figure out what's going on

**Comment by WindyWinston** [comment] 2020-09-01 10:40
Just to be sure, I went to service mode to trigger the glitch, then played through the game without using the warps. When getting to level 8 it still goes back to level 1.

**Comment by mahoneyt944** [comment] 2020-09-01 23:00
Ok so I ran some tests the .hi file is definitely getting heavily modified when you enter the service menu. I did a clean launch, then exited the game and copied the .hi file over to my pc. Then relaunched the game and used the service menu then exited. I then copied that .hi file to pc and compared the data. I'm going to test different scenarios to hone in on the cause. The highscore save works properly but it's saving a piece of memory that is being corrupted. Updates to come.

**Comment by mahoneyt944** [comment] 2020-09-01 23:10
I'm going to temperarily disable the high score save for this game and test without it.

**Comment by mahoneyt944** [comment] 2020-09-02 00:02
Disabling the high score address solves the issue.  When you exit the service menu the .hi file is being saved which is where the glitch comes from.

**Comment by mahoneyt944** [comment] 2020-09-02 00:11
removing this address `0:904010:2:0:7` from the highscore.dat fixes the issue. but im not sure what that does to the highscore save.

**Comment by mahoneyt944** [comment] 2020-09-02 00:55
without the one address, Once I get to level 9 and reset then warping to level 8 goes to 9. These highscore addresses cause the game to malfunction and need rewritten.

**Comment by WindyWinston** [comment] 2020-09-02 09:45
@mahoneyt944 It's probably not worth bothering with this. I just tried MAME32 0.78 and the same hiscore.dat that this core uses and you get the same glitch problem with the service mode. It must be a MAME code issue. Not sure when or if they fixed it in later MAME versions. Maybe there's something in the MAME Gauntlet version history that would signify this being fixed ?

**Comment by mahoneyt944** [comment] 2020-09-02 12:17
The problem is the dat file itself. Saving those addresses for gaunlet messes the game up. To fix it we need new addresses to save from.

**Comment by mahoneyt944** [comment] 2020-09-02 22:36
https://github.com/mamedev/mame/issues/7176
Well I tried to bring this issue to the attention of newer emulators that have this glitch but they have their heads up their asses. So I apologize if this doesn't get fixed. I did what I could.

**Comment by Wilstorm** [comment] 2020-09-03 00:49
@mahoneyt944 - I wouldn't take it personal. I think hiscore.dat was supported, then unsupported for a while (project scope concerns if I remember from many years ago) and now it's distributed as part of the package but Leezer maintains the file. Basically these are few thousand games that had no save "mechanism" once power cycled. If the game works without the hiscore.dat then it's probably outside of the scope of what they care to work on, as they said, unless it's creating a much larger issue. 

I have also read several posts on other forums that have shown some bad blood between the MAME and the Libretro folks. Maybe they have no love for Libretro cores. I have no idea if they were isolated incidents or a larger concern, regardless it might be worth shooting Leezer an email to see if he is aware and knows of a quick fix for Gauntlet. He's a personable and friendly guy.

**Comment by mahoneyt944** [comment] 2020-09-03 01:24
I emailed him, but I believe the issue is the handler not the dat itself. It's being triggered when you exit the service menu and that makes a crap .hi save that breaks the game.

**Comment by Wilstorm** [comment] 2020-09-03 01:42
@mahoneyt944 - Hmm, yeah they shot it down fast without even looking really and also they called you out on being a Libretro dev, irrelevant to the issue. I would say they are pretty much the matriarch of the MAME hierarchy but still they could definitely work on their bed side manner it seems. Can you spin the issue without mentioning the DAT or you never see the issue unless you're using the DAT? Then maybe they'd take a look into it?

**Comment by mahoneyt944** [comment] 2020-09-03 01:45
Well it's complicated. The dat causes the issue because of how the emulation executes the save.  So we need to fix when it saves, not where it's saving

**Comment by mahoneyt944** [comment] 2020-09-03 02:01
@cracyc hey I tagged you here just in case you find anything. I know this isn't the fork you work in but if anything is discovered about gauntlet it might be useful here. Thanks for responding with real interest in bettering mame.

**Comment by dinkc64** [comment] 2020-09-03 02:53
One thing I've learned working in emulation for the past many years:
there's 20 ways to do what needs to be done, but only 1 or 2 of them will end up being the right way.

re: hiscore.dat entry for gauntlet - it's saving data that is used by the game for game-logic - and nothing to do with hiscores - that's where the problem is.  This is not a problem with mame, but a problem with the hiscore.dat entry for gauntlet.

best regards,
- dink

**Comment by mahoneyt944** [comment] 2020-09-03 02:58
@dinkc64 it occurred to me driving to work that gauntlet is saving a .hi file and a .NV file? Maybe the solutions is to remove the .hi save all together? Is the highscore being saved in the nv file too?? Needs tested

**Comment by mahoneyt944** [comment] 2020-09-03 04:33
I'll do more tests when I get home. Need to look at all the games at this address. Some maybe needed some not. I'm guessing someone added these titles to an existing line in the dat without testing or the line in the dat was used before NV saves were functional and it was over looked

**Comment by mahoneyt944** [comment] 2020-09-03 04:54
Looks like the majority of the clones we use are not in the dat anyway. Since the dat breaks this game I'm going to remove it. I think the high score will save in the nv file anyhow but haven't tested. Either way I'd rather the game work then to break it with the dat.

**Comment by mahoneyt944** [comment] 2020-09-03 05:22
@WindyWinston please update from source, delete your .hi, .nv, and .cfg for all gauntlet titles. Then assuming a pi setup, go into `bios/mame2003-plus/` folders and locate/ open the `highscore.dat` file in notepad. Search the file for `gauntlet`. There should no longer be an entry for this game. Then tests that the glitch no longer exists. Try to get a highscore and exit the game. Does the game still save a highscore?

**Comment by Wilstorm** [comment] 2020-09-03 05:34
@dinkc64 - There’s nothing like a little code-porn discussion to get me excited, but don’t tell the wife though she just doesn’t get it. You’re a rockstar and thanks a bunch for the nudge in the right direction! ;)

@mahoneyt944 - I think @dinkc64 pretty much shared the issue with possible steps to correct it. I’m not sure if you know who he is but he knows his stuff.

Here’s a tutorial on how to find the correct memory location for high scores if it helps. https://highscore.mameworld.info/tutorial.htm

I’m just heading out here but I removed the entry and when the game ended, it showed me the high scores (mine wasn’t on it) and that was it, then it just started cycling the attract mode.

**Comment by mahoneyt944** [comment] 2020-09-03 05:43
@Wilstorm for now I removed the entries gauntlet to not corrupt game play. If anyone finds better addresses to save the highscore I'll re add it to the dat. But for now I'd rather the game to work correctly over saving the highscore.

**Comment by mahoneyt944** [comment] 2020-09-03 06:27
@Wilstorm I think this game let's you enter a highscore but only displays the top so many. So if your score was 23rd or something it won't show on the attract screen

**Comment by mahoneyt944** [comment] 2020-09-03 10:02
@WindyWinston I think it's safe to assume that while that highscore address is saving the highscore it's also breaking the game so it's best left out until a better solution can be found.

**Comment by mahoneyt944** [comment] 2020-09-03 10:06
There's also options in the service menu for resetting highscores that need looked at

**Comment by WindyWinston** [comment] 2020-09-03 10:11
Yep, I agree.

The hiscore reset is why I entered the service mode originally to turn it off. Then I found the glitch !

I think some of the new games that Arcadez added maybe don't have an entry in the hiscore.dat or cheat.dat either.

Thanks for trying anyway. I'll let you decide whether to close this or not !

**Comment by markwkidd** [comment] 2020-09-03 10:24
Is the memory address in our hiscore.dat the same as in the most recent
version?


.

**Comment by WindyWinston** [comment] 2020-09-03 10:36
Yes, the v0174 onwards dat and this pre-174 dat use the same addresses.

**Comment by mahoneyt944** [comment] 2020-09-03 10:36
@markwkidd yes it is.

**Comment by WindyWinston** [comment] 2020-09-03 11:55
I notice that you also removed Gauntlet 2 from the hiscore.dat. I'm not familiar with that game so don't know if the service mode affects it.

**Comment by mahoneyt944** [comment] 2020-09-03 11:58
Not sure but it looks like the addresses were found in the same way so it needs tested I guess

**Comment by Wilstorm** [comment] 2020-09-04 02:34
@mahoneyt944 - I’m just shooting a quick text from my phone as I saw your comment but my internet is down when I went to watch Netflix last night. My ISP was supposed show up today but they are a no show after a few calls. I’m hoping tomorrow is the winning ticket as having no internet and no streaming pretty much is the pits when you want to get in front of a PC or watch a show for a bit... =\

You never heard back from Leezer I take it?

**Comment by mahoneyt944** [comment] 2020-09-04 03:04
@Wilstorm yes I did, he said he was pulling the address from the dat for now. 

I also found another bug or at least seems like a bug unrelated to the highscore glitches. If you reach level 9, once you lose and start a new game you will warp to level 9 instead of 8. It seems once you make it to the next highest level you will always warp there instead of the level it says on the warps. Not sure if that's normal or not but it saves this in the nv file so even rebooting it still goes to level 9.

**Comment by mahoneyt944** [comment] 2020-09-04 03:19
Memory maps from 2010

```

/*************************************
 *
 *  Main CPU memory handlers
 *
 *************************************/

/* full map verified from schematics */
static ADDRESS_MAP_START( main_map, ADDRESS_SPACE_PROGRAM, 16 )
	ADDRESS_MAP_UNMAP_HIGH
	AM_RANGE(0x000000, 0x037fff) AM_MIRROR(0x280000) AM_ROM
	AM_RANGE(0x038000, 0x03ffff) AM_MIRROR(0x280000) AM_ROM	/* slapstic maps here */
	AM_RANGE(0x040000, 0x07ffff) AM_MIRROR(0x280000) AM_ROM

	/* MBUS */
	AM_RANGE(0x800000, 0x801fff) AM_MIRROR(0x2fc000) AM_RAM
	AM_RANGE(0x802000, 0x802fff) AM_MIRROR(0x2fc000) AM_READWRITE(atarigen_eeprom_r, atarigen_eeprom_w) AM_BASE_SIZE_MEMBER(gauntlet_state, atarigen.eeprom, atarigen.eeprom_size)
	AM_RANGE(0x803000, 0x803001) AM_MIRROR(0x2fcef0) AM_READ_PORT("803000")
	AM_RANGE(0x803002, 0x803003) AM_MIRROR(0x2fcef0) AM_READ_PORT("803002")
	AM_RANGE(0x803004, 0x803005) AM_MIRROR(0x2fcef0) AM_READ_PORT("803004")
	AM_RANGE(0x803006, 0x803007) AM_MIRROR(0x2fcef0) AM_READ_PORT("803006")
	AM_RANGE(0x803008, 0x803009) AM_MIRROR(0x2fcef0) AM_READ(port4_r)
	AM_RANGE(0x80300e, 0x80300f) AM_MIRROR(0x2fcef0) AM_READ(atarigen_sound_r)
	AM_RANGE(0x803100, 0x803101) AM_MIRROR(0x2fce8e) AM_WRITE(watchdog_reset16_w)
	AM_RANGE(0x803120, 0x803121) AM_MIRROR(0x2fce8e) AM_WRITE(sound_reset_w)
	AM_RANGE(0x803140, 0x803141) AM_MIRROR(0x2fce8e) AM_WRITE(atarigen_video_int_ack_w)
	AM_RANGE(0x803150, 0x803151) AM_MIRROR(0x2fce8e) AM_WRITE(atarigen_eeprom_enable_w)
	AM_RANGE(0x803170, 0x803171) AM_MIRROR(0x2fce8e) AM_WRITE(atarigen_sound_w)

	/* VBUS */
	AM_RANGE(0x900000, 0x901fff) AM_MIRROR(0x2c8000) AM_RAM_WRITE(atarigen_playfield_w) AM_BASE_MEMBER(gauntlet_state, atarigen.playfield)
	AM_RANGE(0x902000, 0x903fff) AM_MIRROR(0x2c8000) AM_RAM_WRITE(atarimo_0_spriteram_w) AM_BASE(&atarimo_0_spriteram)
	AM_RANGE(0x904000, 0x904fff) AM_MIRROR(0x2c8000) AM_RAM
	AM_RANGE(0x905f6e, 0x905f6f) AM_MIRROR(0x2c8000) AM_RAM_WRITE(gauntlet_yscroll_w) AM_BASE_MEMBER(gauntlet_state, atarigen.yscroll)
	AM_RANGE(0x905000, 0x905f7f) AM_MIRROR(0x2c8000) AM_RAM_WRITE(atarigen_alpha_w) AM_BASE_MEMBER(gauntlet_state, atarigen.alpha)
	AM_RANGE(0x905f80, 0x905fff) AM_MIRROR(0x2c8000) AM_RAM_WRITE(atarimo_0_slipram_w) AM_BASE(&atarimo_0_slipram)
	AM_RANGE(0x910000, 0x9107ff) AM_MIRROR(0x2cf800) AM_RAM_WRITE(paletteram16_IIIIRRRRGGGGBBBB_word_w) AM_BASE_GENERIC(paletteram)
	AM_RANGE(0x930000, 0x930001) AM_MIRROR(0x2cfffe) AM_WRITE(gauntlet_xscroll_w) AM_BASE_MEMBER(gauntlet_state, atarigen.xscroll)
ADDRESS_MAP_END



/*************************************
 *
 *  Sound CPU memory handlers
 *
 *************************************/

/* full map verified from schematics */
static ADDRESS_MAP_START( sound_map, ADDRESS_SPACE_PROGRAM, 8 )
	ADDRESS_MAP_UNMAP_HIGH
	AM_RANGE(0x0000, 0x0fff) AM_MIRROR(0x2000) AM_RAM
	AM_RANGE(0x1000, 0x100f) AM_MIRROR(0x27c0) AM_WRITE(atarigen_6502_sound_w)
	AM_RANGE(0x1010, 0x101f) AM_MIRROR(0x27c0) AM_READ(atarigen_6502_sound_r)
	AM_RANGE(0x1020, 0x102f) AM_MIRROR(0x27c0) AM_READ_PORT("COIN") AM_WRITE(mixer_w)
	AM_RANGE(0x1030, 0x103f) AM_MIRROR(0x27c0) AM_READWRITE(switch_6502_r, sound_ctl_w)
	AM_RANGE(0x1800, 0x180f) AM_MIRROR(0x27c0) AM_DEVREADWRITE("pokey", pokey_r, pokey_w)
	AM_RANGE(0x1810, 0x1811) AM_MIRROR(0x27ce) AM_DEVREADWRITE("ymsnd", ym2151_r, ym2151_w)
	AM_RANGE(0x1820, 0x182f) AM_MIRROR(0x27c0) AM_DEVWRITE("tms", tms5220_data_w)
	AM_RANGE(0x1830, 0x183f) AM_MIRROR(0x27c0) AM_READWRITE(atarigen_6502_irq_ack_r, atarigen_6502_irq_ack_w)
	AM_RANGE(0x4000, 0xffff) AM_ROM
ADDRESS_MAP_END
```

**Comment by mahoneyt944** [comment] 2020-09-04 03:50
```
AM_RANGE(0x803120, 0x803121) AM_MIRROR(0x2fce8e) AM_WRITE(sound_reset_w)
```

This one seems updated

**Comment by dinkc64** [comment] 2020-09-04 12:50
mahoneyt944, does the "warp to level 9 instead of 8" bug happen in current version of MAME (0.223 or so)?  IIRC a lot of bugs regarding levels going to the wrong place was fixed with an update to the slapstic emulation a few years back.  If the problem doesn't exist in current MAME I'd suggest porting the fixes to slapstic.

**Comment by mahoneyt944** [comment] 2020-09-04 13:05
Not sure I don't use current mame

**Comment by arcadez2003** [comment] 2020-09-04 13:41
> 
> 
> mahoneyt944, does the "warp to level 9 instead of 8" bug happen in current version of MAME (0.223 or so)? IIRC a lot of bugs regarding levels going to the wrong place was fixed with an update to the slapstic emulation a few years back. If the problem doesn't exist in current MAME I'd suggest porting the fixes to slapstic.

Thanks bigman i'll check the slapstic MAME WIP

**Comment by mahoneyt944** [comment] 2020-09-04 18:44
I changed the memory back after testing.

**Comment by Wilstorm** [comment] 2020-09-05 18:11
@dinkc64 @mahoneyt944 - I just tested current MAME and it doesn't seem to exist but I might be doing it wrong.

The dip switch settings work different with current MAME. When you enter the dip switch settings service mode is off and it won't show any options until you turn it on. After you turn it on it automatically load the options. Once you exit the options it automatically resets the game to the attract mode loop ready for quarters.

I started a game with the warrior, collected the 2 keys on level 1, warped to level 8 and then I would exit the game. When I restarted the game it began at level 1 as it should. 

If I enter the dip switch settings the only option is service mode on/off. When you exit service mode it resets the game so in essence entering the options resets the game. You can pull up the dip switch settings menu and close it as long as you don't turn on service mode or it resets the game if that makes sense.

Also for the life of me can't get a save high score. The lowest score on the Warrior is 4400 at position 10 and I had a score of over 6000 on level 8 but once my health runs out it doesn't ask me to enter my initials. It just goes back to the attract mode.

**Comment by mahoneyt944** [comment] 2020-09-05 18:15
@Wilstorm the highscore is based per quarter. So when you put too many coins in you score isn't worth as much so you don't get a highscore even if the value is technically higher

**Comment by Wilstorm** [comment] 2020-09-05 20:58
@mahoneyt944 - Ah, ok I will retest. Could you share the steps to test for the issue if it helps and I’ll see if it’s happening in the current version of MAME.

Basically the current MAME dip switches are service mode on/off. When you enter or exit service mode to get to the options it quits your current game.

No .nvram file either it’s .eeprom for Gauntlet.

**Comment by mahoneyt944** [comment] 2020-09-05 21:10
The service menu glitch is fixed by removing the highscore dat. That level glitch is tested by warping to level 8, beat level 8 to warp to 9. Once you lose and start a new game. Warps go to level 9 instead of 8

**Comment by Wilstorm** [comment] 2020-09-06 03:10
@mahoneyt944 - It does exist in current MAME during the same session. If you exit and restart then it works properly again. I didn't delete any files between sessions. 

Yeah and I pretty much suck and couldn't do it with one quarter so I couldn't get on the board.

**Comment by dinkc64** [comment] 2020-09-06 04:45
Now I wonder, is that level warp glitch caused by a bug in the game or a bug in the slapstic emulation?  Does anyone know someone with a Gauntlet pcb that can test this?

**Comment by Wilstorm** [comment] 2020-09-06 15:57
@dinkc64 - I agree this down to brass tacks. Is this a bug yet to be fixed or is this exactly as the arcade version worked. 

I don’t know anybody with a PCB but if I can do any other testing to help with anything just let me know.

**Comment by arcadez2003** [comment] 2020-09-06 16:09
@dinkc64 I've looked through the gauntlet driver + slapstic MAME WIP and on MAME testers and there is no mention 
of this issue or indeed any fix which was done to sort it.

It might be a problem with the original game code on the pcb or an unrelated update to the slapstic which inadvertently
fixed it, anyhow im not prepared to look into this any further as the easiest way to just avoid it is to not enter the service 
mode in the first place which im sure 99% of users wont do anyway.

But if anyone else wants to dig deeper into this mystery then feel free :)

**Comment by Wilstorm** [comment] 2020-09-06 16:37
> or if as people are saying this doesn't happen in the
current MAME cores an unrelated update to the slapstic which inadvertently fixed it.??

I downloaded the current version of MAME yesterday and the warp bug exists still (I know that’s outside the scope of the issue) but the service mode bug can’t be tested really in the current version just because of the differences of how mane2003-plus and the current version MAME load the DIP switch settings.

In Plus you can get in and out of the DIP switch settings without the game resetting to test it but on the current version of MAME the game resets entering and exiting the service mode (to get to the DIP switch settings) so you never really know.

**Comment by Wilstorm** [comment] 2020-09-06 16:38
I agree though there probably isn’t much to do unless someone has a real PCB to do some additional testing.

**Comment by mahoneyt944** [comment] 2020-09-06 17:22
There are two separate bugs we were testing. 

Bug 1: exit service menu warp issue. This was solved by removing the highscore dat.

Bug 2. General warp issue. This is done by starting the game, warp to level 8, beat level 8 which warps you to level 9. Then die. Coin up again and begin a new game. warps will go to level 9. This saves in the nv file. No fix for this yet.

I'm going to close this since the initial issue is fixed and bug 2 needs tested against a real pcb.

**Closed by mahoneyt944** 2020-09-06 17:22 UTC

**Comment by arcadez2003** [comment] 2020-09-27 13:10
@mahoneyt944  Been checking the ole MAME WIP of late looking for fixes for big name games we're missing in this core, 
and i bumped into a very similar fix which was done for Star Wars and The Empire Strikes Back..............

0.104: Fixed NVRAM handling in Star Wars/ESB (only affects test mode) [Mathis Rosenhauer].

Seeing as their both Atari games it might be worth checking this out to see if it can be adopted for the Gauntlet games.
