### ISSUE TITLE
Missing inputs in Assault on Namco S2

### ISSUE THREAD

**Issue by vaguerant** [libretro/mame2003-plus-libretro#1658] opened 2023-12-09 12:59 UTC
# Problem software/hardware
* Assault (`assault`) on Namco S2 (`namcos2.c`)

# Description
Assault is a tank game using two joysticks. The left joystick controls left-side movement and the right joystick controls right-side movement. In MAME 2003 Plus, the right stick a) cannot be remapped in the RetroArch interface and b) is missing the Up and Down inputs, rendering the game unplayable since it's impossible to drive forward or backward without the right side.

# Additional notes
*Possibly* an endian issue since I'm running on the big-endian PPC32 Wii U; has not been tested on little-endian.

Controls for Assault are set up here, I can't read code at all but it looks pretty normal except for the `/* fake port15 for single joystick control */`.
https://github.com/libretro/mame2003-plus-libretro/blob/59e49400fa6fc95237885c06732dfeef27687dec/src/drivers/namcos2.c#L1336-L1381

Same section in historic-mame if it's helpful:
https://github.com/mamedev/historic-mame/blob/6f03755e212f33ae6e4681d56351bf3c44f20916/src/mame/drivers/namcos2.c#L1182-L1219

# Build tested
* 59e4940 (latest commit as of this filing) on RetroArch Wii U

**Comment by arcadez2003** [comment] 2023-12-09 14:09
Yes the problem is on the RA side as this game always controlled ok for me using my standalone xbox MAME core.
in the meantime until a fix for this issue is found you could turn on the fake port and the game in theory should contol 
via one joystick rather than two....

	PORT_START	/* fake port15 for single joystick control */
	PORT_BIT( 0x01, IP_ACTIVE_LOW, IPT_JOYSTICK_UP | IPF_CHEAT )
	PORT_BIT( 0x02, IP_ACTIVE_LOW, IPT_JOYSTICK_DOWN | IPF_CHEAT )
	PORT_BIT( 0x04, IP_ACTIVE_LOW, IPT_JOYSTICK_LEFT | IPF_CHEAT )
	PORT_BIT( 0x08, IP_ACTIVE_LOW, IPT_JOYSTICK_RIGHT | IPF_CHEAT )
	PORT_BIT( 0x10, IP_ACTIVE_LOW, IPT_BUTTON2 | IPF_CHEAT )
	PORT_BIT( 0xe0, IP_ACTIVE_LOW, IPT_UNUSED )

You should be able to trackdown the above via the games input controls.

**Comment by mahoneyt944** [comment] 2023-12-09 14:50
I don't believe we describe the controls in retroarch for dual stick games. So that maybe why it's not mappable in RA. However you should be able to remap these in the mame menu directly. 
https://github.com/libretro/mame2003-plus-libretro/blob/59e49400fa6fc95237885c06732dfeef27687dec/src/mame2003/mame2003.c#L753-L773

**Comment by vaguerant** [comment] 2023-12-10 06:22
Even using the MAME input mapper, I still can't map the (physical) right stick Up/Down. Left/Right are already mapped normally and I can assign them as I'd expect, but Up/Down aren't recognized in the MAME mapper at all, it behaves as if I haven't pressed anything if I select a button to map then move the stick Up or Down. Again, Left/Right works perfectly, so it's not that the stick isn't read at all, just one axis of it.

**Comment by mahoneyt944** [comment] 2023-12-10 16:31
That must be a frontend issue then... are you using the most recent commit for the core as well?

**Comment by mahoneyt944** [comment] 2023-12-10 20:03
Confirmed working with current master and official RA on Android.

**Comment by arcadez2003** [comment] 2023-12-10 20:32
Well as i said use the single joystick hack in the meantime until a solution is found

**Comment by mahoneyt944** [comment] 2023-12-12 00:12
@vaguerant which commit of this core are you on? Which frontend and rev are you using?

**Comment by vaguerant** [comment] 2023-12-13 05:59
At time of filing, I was on:
* MAME 2003-Plus 59e4940
* libretro/RetroArch@a8ffa50

I just updated the MAME 2003-Plus core, so now I'm on:
* MAME 2003-Plus 59e4940
* libretro/RetroArch@44132c4

Behavior is still the same on the newer frontend build.

**Comment by mahoneyt944** [comment] 2023-12-13 06:11
I'm wondering if this is a wii input driver issue. Do any dual stick games work for you? Like robotron or crazy climber?

**Closed** 2023-12-13 10:27 UTC
