### ISSUE TITLE
Rootbeer Tapper and Tapper High Scores:

### ISSUE THREAD

**Issue by Loggahead** [libretro/mame2003-plus-libretro#301] opened 2018-07-03 21:33 UTC
Is there an issue with highscores not saving on rbtapper and tapper?  Not sure if this is something new or something you already knew about but I can confirm on my rpi3b running retropie 4.4 I found that neither of those roms are saving highscores.

**Comment by grant2258** [comment] 2018-07-04 03:53
not all games save hi scores if no games are saving high scores that would be an issue

**Comment by grant2258** [comment] 2018-07-04 05:57
@markwkidd fwiw I believe the changes to the mame re-mapper caused this issue because the .cfg files arent saving either even when it enabled.

**Comment by grant2258** [comment] 2018-07-04 07:30
actually scrub them comments teh hi scores and cfg is saving forgot retropie uses the content dir duh

**Comment by Loggahead** [comment] 2018-07-05 13:13
Also for what it is worth, it appears to be affecting just Bally Midway games.  I confirmed that Timber is also not working.  I haven't tried some of the others like Rampage, Spy Hunter, etc. yet.

**Comment by grant2258** [comment] 2018-07-05 15:03
I think all the mcr3 will be effected at least mcr1 should be fine though

**Comment by Loggahead** [comment] 2018-07-05 16:01
In your opinion is it a fixable issue for mame2003+?  I'll do some testing and see if it also happens in mame2010 to see if it is just happening in 2003+.

**Comment by grant2258** [comment] 2018-07-05 17:24
all i can do is test with later on when i get round to it ill know for sure when i change the code. Is fba saving midway hiscores ?

**Comment by Loggahead** [comment] 2018-07-05 18:30
Not sure about fba.  I'll test them out tonight with in .43 if they are available and will post back.

**Comment by markwkidd** [comment] 2019-01-07 05:09
@Loggahead can you confirm whether this is still a problem in the latest builds?

**Comment by grant2258** [comment] 2019-01-07 11:54
nothings changed in respect this so its still and issue no ones fixed it

**Comment by markwkidd** [comment] 2019-01-19 18:56
I can confirm that scores are still not saving in `tapper` in the current build. Tapper did save its own score tables, so I believe these scores should be saved in the `tapper` `nv` file that is generated.

**Comment by mahoneyt944** [comment] 2020-05-15 09:58
Fixed https://github.com/libretro/mame2003-plus-libretro/pull/780

**Comment by mahoneyt944** [comment] 2020-07-26 22:08
This issue can be closed now as it's now fixed.

**Closed** 2020-07-27 00:27 UTC

**Comment by QPCloudy** [comment] 2022-03-29 15:32
> This issue can be closed now as it's now fixed.

Hello. running Mame2003 with 0.78 rom set, Tapper and TapperA both are not saving the high score list. It does not appear to be fixed. Any suggestions?

**Comment by mahoneyt944** [comment] 2022-03-29 20:31
This is mame2003-plus, not mame2003. Update mame2003-plus from source and select it as the emulator to play tapper
