### ISSUE TITLE
Lightgun cursor offset in jpark and luckywld

### ISSUE THREAD

**Issue by StormedBubbles** [libretro/mame2003-plus-libretro#1211] opened 2021-11-30 03:23 UTC
Hello,

Like what was described in #1203 for lethalen, on Pi 4 with RetroPie, these two games have alignment issues when the xy device is set to "lightgun." Neither of these games has a calibration menu.

jpark: both players are off. Player 1 is offset to the left, while player 2 is offset to the right

luckywld: player 1 is fine, but player 2 is offset to the right.

**Comment by mahoneyt944** [comment] 2021-11-30 05:36
Hmm there seems to be something else at play with luckywld. This is one of the games I bootstrapped to include the calibration. You can access the gun calibration by entering the "service mode". Then pressing "service 1" twice. These are separate buttons so don't confuse them. I've re-calibrated just to double check but it appears that player 2 has different scaling or a different range? It matches up on the sides but loses some in the middle for whatever reason. I wonder if the game used internal scaling to match the crt curvature...I'll verify the code and I'll have to test newer mame to see if the same thing occurs or not.

**Comment by mahoneyt944** [comment] 2021-11-30 05:47
@grant2258 should this be 255 ? I think this is scaling the bitmap size with the lightgun range?

https://github.com/libretro/mame2003-plus-libretro/blob/755e64ed8c7f1fdc5d69e65084a3355c51107937/src/vidhrdw/namcos2_vidhrdw.c#L630-L639

**Comment by mahoneyt944** [comment] 2021-11-30 06:12
Jpark seems to actually be an analog stick not a true lightgun. As seen here
https://github.com/mamedev/mame/blob/79738b4cb44a039bd6bf04632585ffeb9bb4648d/src/mame/drivers/segas32.cpp#L1864-L1888

Likely just needs updated

**Comment by grant2258** [comment] 2021-11-30 08:03
That jurasic park isint a lightgun game http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=jpark&arcade_only=0&autosearch=1 check the cabnit picture top left

**Comment by mahoneyt944** [comment] 2021-11-30 09:34
> That jurasic park isint a lightgun game http://adb.arcadeitalia.net/dettaglio_mame.php?game_name=jpark&arcade_only=0&autosearch=1 check the cabnit picture top left

Created a PR to fix this.

**Comment by StormedBubbles** [comment] 2021-11-30 13:33
Thanks for all of the responses. On Jurassic Park: yes, it is controlled via sticks a la "gun on a stick" games like Terminator 2 (term2). For reference, term2's in-game cursor lines up perfectly with my guns in 2003-plus.

**Comment by mahoneyt944** [comment] 2021-11-30 14:01
@StormedBubbles I updated jpark to the proper analog inputs. Try testing the latest commit.

**Comment by StormedBubbles** [comment] 2021-11-30 14:23
Thank you. Here is my experience with the latest commit:

**When using a controller:** Input is smooth when using an analog stick on a controller, but the cursors do not start or re-center at the exact center of the screen.

**When using a Sinden gun:** Gun behavior is now very erratic. I know jpark isn't a true lightgun game, but before, the gun had smooth movement and just had an offset between where I was aiming and where the in-game cursor appeared on screen.

**Comment by StormedBubbles** [comment] 2021-11-30 16:34
Just wondering about something: I think that jpark should still be designated as a lightgun game even though it didn't have an actual "lightgun." 

If you compare with Terminator 2 (a game labeled as a lightgun game that works well in 2003plus with the Sinden guns), you'll see that they are functionally similar. Terminator 2 just had a plastic shell of a gun mounted onto a stick that was used by the players to move the crosshairs around the screen. It did not do any light sensing and is not technically needed. It could be removed and replaced with something that looks similar to what is on jpark's cabinet and still function the same. Likewise, the gun shell could be mounted over the jpark stick and function similarly.

**Comment by mahoneyt944** [comment] 2021-11-30 23:45
@StormedBubbles I think the issue is that jpark is not suppose to center in the middle of the screen. Each player is suppose to center on their side of the screen. 

There were min and max values used previously that are dropped in newer mame, likely what made the lightgun track here before. I'll look more at it.

**Comment by StormedBubbles** [comment] 2021-12-01 05:01
Thank you! I really appreciate the effort and explanations.

**Comment by mahoneyt944** [comment] 2021-12-03 13:28
@StormedBubbles so I did some digging with luckywld and found this https://github.com/mamedev/mame/blob/f85d81986d72e029db20a484313794832999e24d/src/mame/drivers/namcos2.cpp#L1406-L1409 which describes why the p2 mame crosshair is not aligned with the games internal crosshair. This is not a bug it's just how the original p2 gun was.

**Comment by StormedBubbles** [comment] 2021-12-03 14:34
Thanks for checking on that! I was able to get luckywld's internal crosshairs for P2 to match up with my gun sight by purposely calibrating that gun with an offset in the game's service menu. I do notice that P2's (in-game) cursor gets sort of trapped on the left side of the screen and encounters kind of a dead zone there. I'm not sure if that's the right term, but there's a vertical strip near the very edge of the left side side of the screen that will grab/snap the P2 cursor when it gets too close and throw off the gun's horizontal tracking until you move back towards the center of the screen. Vertical tracking appears okay in that strip. This happens with and without the purposely offset calibration.

**Comment by mahoneyt944** [comment] 2021-12-05 13:42
If you delete luckywld.nv in the save directory then run luckywld fresh does this happen without trying to calibrate yourself? I cant replicate any deadzone areas.

**Comment by StormedBubbles** [comment] 2021-12-05 16:24
Ah, I guess my notes were off. Sorry about that! Without the calibration, it seems good. Thanks for investigating!

The in-game calibration has targets on the far left and right sides of the screen. In order to line up the cursor for P2 with my sight, I have to fire to the right of the target on the left side of the screen. It is only possible to fire a little to the right of the other one, so it looks like I make the game think the left side of the screen is wider than the right (for P2 only). For player 2, it just takes more effort to get the cursor to escape a small strip of the screen on the left side. 

It's not really an issue then. It still works well enough with the calibration. The game has internal cursors anyway for both players, so I can just rely on those if the calibration becomes too annoying and I delete the .nv file.

For jpark, would it be possible to control the cursors with mouse/lightgun again? Since the switch from lightgun to analog for that game, the cursors jump all around the screen without much rhyme or reason.

**Comment by mahoneyt944** [comment] 2021-12-06 05:19
I think so, I'll need to experiment first and once I have something you'll have to test it out.

**Comment by StormedBubbles** [comment] 2021-12-06 05:35
Okay, that would be great! I am happy to test anything you can provide.

**Comment by mahoneyt944** [comment] 2021-12-06 09:11
Do me a favor, test alien3 and let me know how well that game tracks for you. Since they share a common hookup.

**Comment by StormedBubbles** [comment] 2021-12-06 16:26
alien3 works well by default. The in-game cursors and shots line up with the sights of my guns without any adjustments needed. The life meters for the players seem to constantly flash, but based on a handful of YouTube videos, that's how it was supposed to be. What a terrible design choice! 🤣

**Comment by mahoneyt944** [comment] 2021-12-07 09:51
I pushed a commit that should allow the lightgun to work again. Though x will still likely be off like it was previously. Seems like this game might have a similar side effect as luckywld where it expects the shooting angle to be offset for each player giving the miss alignment.

**Comment by mahoneyt944** [comment] 2021-12-07 11:12
Also since the game is still registered as an analog stick you'll have to disable "center joystick axis for digital controls" located under core options-> input... as it will interfere with a lightgun input.

**Comment by StormedBubbles** [comment] 2021-12-07 21:42
Thanks for the update! I deleted the jpark nvram and cfg before testing this.

The gun tracking is definitely better in this update than the update in which the game was changed to analog controls, but it still has some erratic behavior. It does seem a bit better with the option you mentioned disabled. 

I have some amount of control if I make very subtle movements with the gun while only pointing in a very small area on the screen. It does feel as if I'm trying to control an analog stick with a mouse. The cursor jumps around very easily no matter how careful I try to be.

I played around with the settings for dead zone (core options) and analog sensitivity (tab menu) and didn't notice an improvement.

**Comment by mahoneyt944** [comment] 2021-12-08 05:04
Yeah that's essentially what's happening. I'm not sure I can do much about this one, unless I change it back to lightgun inputs with the slightly improved read and writes I updated....being that this game has a slew of gfx issues anyhow it probably won't hurt to be set to lightgun.

**Comment by mahoneyt944** [comment] 2021-12-08 05:08
Pushed an update.

Delete jpark.cfg, jpark.nv, and you can set the core option to center joystick for digital controls back to enabled as this doesn't effect lightguns.

**Comment by StormedBubbles** [comment] 2021-12-08 14:05
Thanks! That's definitely much better. The guns track very well with the lightgun input enabled. I notice that the in-game crosshairs/shots are offset from the mouse cursor / gun sight for both players. The in-game cursor is always to the left of where player 1 is pointing and to the right of where player 2 is pointing. It seems like the offset is a constant amount. Not sure if that is adjustable on the back-end.

For reference, the in-game crosshairs/shots do line up well when using FBNeo, but this particular game has a lot of performance issues in that emulator. Aside from the graphical glitches I noticed on the continue screen, the game runs considerably better on 2003plus.

**Comment by mahoneyt944** [comment] 2021-12-08 22:57
Interesting fbneo has some notes about this I may be able to port. https://github.com/finalburnneo/FBNeo/blob/7f16d14b78be84c8c38d47290ca7c6f177a660c4/src/burn/drv/sega/d_segas32.cpp#L2225-L2251

**Comment by StormedBubbles** [comment] 2021-12-08 23:03
Also, sorry to bring up luckywld again, but I'm now realizing that player 1's gun movement also steers the car left and right when that should only be done with the steering wheel. 

Currently, I am able to steer the car with a controller while simultaneously shooting with a gun (both controlling P1's inputs). It's just that the car left/right movement is duplicated on the gun. I happened to be looking at fbneo the moment you posted your message and found this for the steering:

https://github.com/libretro/FBNeo/commit/9a243870f41d5dfd9c13ae7b0f6b98690e385f20

**Comment by mahoneyt944** [comment] 2021-12-09 01:47
You have to change the mapping for this in the mame menu. Core options-> system -> display mame menu -> enable. Then close RetroArch menu. In the mame menu select "input this game", then change the "dial" control mapping. Press A button to select the input then press the button you want to change it to.

**Comment by mahoneyt944** [comment] 2021-12-09 07:51
With help from dinks notes about the tracking in jpark, I believe my latest commit should fix the tracking issue for you.

Delete jpark.cfg and jpark.nv and retry.

**Comment by StormedBubbles** [comment] 2021-12-09 13:24
jpark is good now. Thanks so much!

Something is still weird with the controls on luckywld. No matter what I map the dial to, the gun movement still controls the car's steering. It happens even if I just map the dial to random keyboard keys alone and remove the original mappings for the dial.

**Comment by mahoneyt944** [comment] 2021-12-09 13:54
Hmm I wonder if the lightgun also reads as a mouse. Because then the mouse tracking would pick it up too even if the dial isn't mapped. @grant2258 I'm not sure there would be a solution to this with our current input status.? Thoughts?

**Comment by grant2258** [comment] 2021-12-09 22:43
the solution is at driver level change it to dial2

**Comment by mahoneyt944** [comment] 2021-12-10 03:09
Hmmm that might still interfere with player 2's lightgun. dial3? But this seems kind of wonky, though effective.

**Comment by mahoneyt944** [comment] 2021-12-10 03:31
Do we ever want a lightgun to override a dial or paddle? Maybe we need a override check in place to prevent this behavior?

**Comment by grant2258** [comment] 2021-12-10 08:08
no easy solution for this apart from re writing how analog works on this core or use a later mame.

**Comment by mahoneyt944** [comment] 2021-12-10 11:03
Yeah it would be a big project, I'd be interested though if we had a team working on it to bounce ideas around though.

Can we at least trace what's happening exactly and where? I'm guessing the lightgun overrides the analog which overrides the dial. Placing our rescaled absolute input into a relative one?

**Comment by grant2258** [comment] 2021-12-10 12:28
nope tahts not whats happening at all its order of precedence per device

**Comment by mahoneyt944** [comment] 2021-12-10 12:31
What's the order?

**Comment by grant2258** [comment] 2021-12-10 12:41
https://github.com/libretro/mame2003-plus-libretro/blob/5ad3eafd3a22c6b75dd9286d666b66c7f049d350/src/inptport.c#L918-L950

dont know how much of this code has been changed will all need checked you probles with the analog stick will probably be the deadzone

**Comment by mahoneyt944** [comment] 2021-12-10 13:14
The deadzone isn't calculated in the rescale_analog function anymore. So it shouldn't effect the lightgun if it's just swapping it's value into the analogs data structure. Right?

**Comment by mahoneyt944** [comment] 2021-12-10 13:23
Come to think of it, is maybe this is why switching to the pointer and back messing up the scaling. Bit it works for lightgun with this hack

**Comment by mahoneyt944** [comment] 2021-12-10 13:46
Odd that switching between mouse lightgun and off works fine. Bit once you switch to pointer the scaling fails. I wonder if this hack is related or not.

**Comment by grant2258** [comment] 2021-12-10 22:38
no really we talked about this before when operation thunderbots was fixed the code needs more conditions added if you want to fix it. all the code is in inptport.c it not too bad to follow either

**Comment by mahoneyt944** [comment] 2021-12-10 22:41
I've skimmed through there but it's harder to follow on a phone screen. Need a big monitor lol

**Comment by grant2258** [comment] 2021-12-10 22:44
just finished work want to get a nice cuppa something to eat. Cars nearly done as well new steering rack and subframe and steering rack is on just need to put all the other bits back on now. Roughly track it and see if it still goes haha.

**Comment by mahoneyt944** [comment] 2021-12-10 22:47
What kind of car is it?

**Comment by grant2258** [comment] 2021-12-10 22:47
mazda 6

**Comment by mahoneyt944** [comment] 2022-01-20 05:49
Closing this and moving the focus to the new issue. #1275

**Closed by mahoneyt944** 2022-01-20 05:49 UTC
