### ISSUE TITLE
switch black screen after loading rom 1.9.1-1.9.3

### ISSUE THREAD

**Issue by lencil** [libretro/mame2003-plus-libretro#1054] opened 2021-05-23 06:53 UTC
on switch, 1.9.3 will black screen.
work fine on 1.8.9

**Comment by mahoneyt944** [comment] 2021-05-23 11:21
Post a debug level log to analyze.

**Comment by ckeisc** [comment] 2021-05-23 19:05
If you wait for 5-10 minutes, does it work? @lencil

**Comment by markwkidd** [comment] 2021-05-23 19:31
Other than wondering if this is a frontend prob ok em, there have been some updates to the libretro common file functions during the last year: https://github.com/libretro/libretro-common/commits/master/file/archive_file.c

**Comment by mahoneyt944** [comment] 2021-06-23 04:54
@ckeisc can you confirm if using retroarch 1.8.9 with our current commit of mame2003-plus works or not? This will help us determine if the issue is within the core or retroarch

**Comment by ckeisc** [comment] 2021-06-24 00:58
@mahoneyt944 I only have access to a 3DS build which is statically compiled - the core contains the whole frontend, so can’t try separate combination of core and frontend.

**Comment by mahoneyt944** [comment] 2021-11-07 18:03
After confirming to be improved by this user https://www.reddit.com/r/RetroArch/comments/pfd69e/mame_2003plus_on_retroarch_3ds_takes_forever_to/?utm_source=share&utm_medium=mweb I'm going to close this issue. It's recommended to change the core option "autosave hiscore" to disabled.

**Closed by mahoneyt944** 2021-11-07 18:03 UTC
Labels: bug

**Comment by mahoneyt944** [comment] 2022-01-28 00:26
3ds and switch should be fixed now with or without using cheat.dat. please use the latest commit at the time of this post.
