### ISSUE TITLE
[android arm7] gtg2j reset freeze

### ISSUE THREAD

**Issue by telanus** [libretro/mame2003-plus-libretro#166] opened 2018-05-03 07:50 UTC
Hi 

I've got mame2003+ to run nicely with the roms I have. But I've encountered a small bug, if you reset the game using retroarch's reset in the quick menu, it'll freeze retroarch, sometimes android's "retroarch is not responding" (or something like that) will come up and allow you to terminate android, other times you need to reset your tablet to get out of retroarch.

I'm using a nightly from last week and the latest core from the online updater, on a generic android  5.1 tablet

**Comment by grant2258** [comment] 2018-05-03 08:04
@telanus do you get the same problem if you reset games om mame 2003 the old way through the ui?

**Comment by telanus** [comment] 2018-05-03 09:02
@grant2258 yes, just downloaded mame2003 and it also crash when I reset a game

**Comment by grant2258** [comment] 2018-05-03 09:04
is it any game or one game in particular

**Comment by grant2258** [comment] 2018-05-03 16:44
just wanna try debug whats going on

**Comment by SapphireTactician** [comment] 2018-05-03 20:50
I can't reproduce the bug on Android 7.0.

>on a generic android 5.1 tablet

Time for a new tablet if you ask me.

**Comment by markwkidd** [comment] 2018-10-15 19:05
@telanus I don't think there is anything more that can be done on this issue -- possibly if you can generate a log there will be a clue: https://docs.libretro.com/guides/generating-retroarch-logs/

If you aren't able to generate a log then I will close this issue due to no way forward.

**Closed** 2018-10-17 04:12 UTC
