### ISSUE TITLE
sonic3mb Sonic bootleg

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-plus-libretro#1870] opened 2024-11-01 15:42 UTC
@arcadez2003 I noticed there's a minor bug with the water level. Seems like a core bug, like a scroll or wraparound issue.

**Comment by mahoneyt944** [comment] 2024-11-01 15:54
Should look like this
![Screenshot_20241101-115354](https://github.com/user-attachments/assets/b585844f-6d10-4026-9a73-470ed871a912)

**Comment by arcadez2003** [comment] 2024-11-01 18:25
Thanks for the headsup i'll check the code when it was first added

**Comment by grant2258** [comment] 2024-11-01 21:21
Its not just the water fall the pallet seems to change at times at certain point in the game. You walk back and it goes normal hit a point and it changes.

**Comment by grant2258** [comment] 2024-11-01 21:28
@arcadez2003 where is the video code based for the segac2 I know there has been a few updates can take a sneak at some point dont want to revert anything you've done already though.

**Comment by arcadez2003** [comment] 2024-11-01 22:25
I'd to see it in action on latest MAME to see if the issue happens there as TBH it's a bootleg
sometimes ya get game problems due to nature of the beast.

**Comment by grant2258** [comment] 2024-11-01 23:09
Its not happening in mame here is a recording of it. 
[sonic3mb-241101-230437.zip](https://github.com/user-attachments/files/17604759/sonic3mb-241101-230437.zip)

**Comment by arcadez2003** [comment] 2024-11-01 23:22
Yeah i see it now doesn't look good that would annoy most players

**Comment by grant2258** [comment] 2024-11-01 23:33
Well im not complaining like. It just it happens at some points @mahoneyt944 pointed one out there is quite a few places it happens. If you know what your looking for its easier to catch.

**Comment by arcadez2003** [comment] 2024-11-01 23:41
Yeah at this point in MAME alotta the Sega video code is merged by the time the other core 
i work on MAME106 rolls around they started to seperate it all out, the video code for this game
is in vidhrdw/segac2.c

**Comment by grant2258** [comment] 2024-11-01 23:51
ill test the core before we made these changes to system18 amd let know. I cant do it tonight though mate but its best to do that rather than checking code that might not have caused it.

**Comment by arcadez2003** [comment] 2024-11-01 23:55
Humour me try this....

in static MEMORY_WRITE16_START( barek2ch_writemem )

try 	{ 0xc00000, 0xc0001f, segac2_vdp_w },			/* VDP Access */

**Comment by arcadez2003** [comment] 2024-11-02 00:00
On a seperate note i added Jurrasic Park when i last tried out this game on my xbox MAME72
core it booted but would not coin up so all i could do was watch the attract mode, the game
looked ok gfx wise but im sure some sounds were missing.

Anyway according to notes in the driver it should coin up and work atleast maybe we'll luck
out and it will do so here if not then i'll simply remove it from the builds until such a time as
a proper simulation of the PIC MCU which handles this is finally done.

**Comment by grant2258** [comment] 2024-11-02 00:15
sorry i was checking the c2 video changes

https://github.com/libretro/mame2003-plus-libretro/commits/master/src/vidhrdw/segac2_vidhrdw.c Ill try at at 

[Sega Megaplay Video Changes](https://github.com/libretro/mame2003-plus-libretro/commit/8bd3f6ec85354bea526d32fc7520f48ad756df2f)

and the one before it will also test that game if i have it.

**Comment by mahoneyt944** [comment] 2024-11-02 00:23
There's some notes in the top of the driver describing some scrolling issues and fixes, perhaps there's a simple fix we missed somewhere?

**Comment by arcadez2003** [comment] 2024-11-02 02:33
> sorry i was checking the c2 video changes
> 
> https://github.com/libretro/mame2003-plus-libretro/commits/master/src/vidhrdw/segac2_vidhrdw.c Ill try at at
> 
> [Sega Megaplay Video Changes](https://github.com/libretro/mame2003-plus-libretro/commit/8bd3f6ec85354bea526d32fc7520f48ad756df2f)
> 
> and the one before (tomorrow) I will also test that game if i have it can do that now. Jpark seems to work but you have to press start 1 and start 2 to get credits in and it puts a few in.

Ah so that was it you needed to press both coins at the same time well only having one xbox
gamepad it was not something i could do ha ha, i suppose i could hack it and make both coins
into one so to speak.

Anyway thanks for trying it out i might as well add Twinkle Tale it'll have a similar issue around the
coins though

**Comment by arcadez2003** [comment] 2024-11-02 02:43
> There's some notes in the top of the driver describing some scrolling issues and fixes, perhaps there's a simple fix we missed somewhere?

Sure it's possible but it might just be the game doesn't like our ole Sega video code grant will
know all about that hence he's had to update it so often :)

**Comment by grant2258** [comment] 2024-11-03 00:29
Well its not something we have done the same issue is on my test core with mame095. I think arcadez is right the pallete updates between 108 109 ish whenever the spilt started addressed this.

**Comment by arcadez2003** [comment] 2024-11-03 12:53
I dunno TBH the palette changes were for two Segac2 games Ribbit and Twin Squash so they
could remove some hack workarounds, but hey that could also have benefited some other games
using the same code.

Anyway i'll Twinkle Tales shortly then look at one other game we dont Support Bare Knuckle 1
but that would require 6 button MESS genesis gamepad support.

**Comment by grant2258** [comment] 2024-11-07 23:36
twinkle tails does work I just tested it there m8

**Comment by arcadez2003** [comment] 2024-11-08 00:11
Alright good to know so they're all working allbeit Sonic 3 has some gfx issues

**Comment by grant2258** [comment] 2024-11-08 00:14
better than not working at all if you ask me I think the mame100u2 i think it was would fix this issue but its right in the middle of a splitting the driver up as well.

**Comment by arcadez2003** [comment] 2024-11-08 01:55
> better than not working at all if you ask me I think the mame100u2 i think it was would fix this issue but its right in the middle of a splitting the driver up as well.

Defo could be that for sure im still wondering about the mem map though namely one of the Rom
addresses, basically the map is the same as Top Shooter with some io additions i assume i copied it
and then changed the rom address value so that Bare Knuckle 2 would boot.

But maybe that is what is throwing off the gfx in sonic 3.?? or maybe not but i feel it's worth 
trying the original address Top Shooter was using as that shares the same map md_bootleg_map
which Sonic 2 and 3 in current mame it'll only take ya two secs to switch it and another 20 secs to see what happens.

Try this....
static ADDRESS_MAP_START( barek2ch_readmem, ADDRESS_SPACE_PROGRAM, 16 )
	AM_RANGE(0x000000, 0x0fffff) AM_READ(MRA16_ROM)					/* Cartridge Program Rom */

static ADDRESS_MAP_START( barek2ch_writemem, ADDRESS_SPACE_PROGRAM, 16 )
	AM_RANGE(0x000000, 0x0fffff) AM_WRITE(MWA16_ROM)

**Comment by grant2258** [comment] 2024-11-09 01:48
will try this in a bit mate and let you know

**Comment by arcadez2003** [comment] 2024-11-09 12:21
Aye nae hurry bigman it's a longshot anyway as like you i think it's the palette handling in or ole 
genesis video but i just wanna rule it out :)

**Comment by grant2258** [comment] 2024-11-09 14:57
I hear you on that its not impossible to live with could mark it as imperfect graphics.

**Comment by arcadez2003** [comment] 2024-11-09 23:38
Ok to wind this up after talking with dink and searching with google it seems the problem is
that Sonic 3 handles the palette for the water sections differently from the other games.

Rather than the update you spoke about we'd idealy need to port sections of the genesis video
code across from MESS to fix this maybe one day ok then i'll close this down for now.

**Closed by arcadez2003** 2024-11-09 23:38 UTC

**Comment by grant2258** [comment] 2024-11-10 05:33
Still the same mr arcadez this one want one of us to do some graft. I might mess about with this on my port at some point to see if it works before changing shed load of drivers in the segac2 to see that is not working!
