### ISSUE TITLE
backport Lunar Lander control fixes?

### ISSUE THREAD

**Issue by Wilstorm** [libretro/mame2003-plus-libretro#580] opened 2019-01-10 16:13 UTC
I've been testing a few more of the vector games and I noticed Lunar Lander (llander) fires the thruster full blast when turning left. It doesn't happen when turning right. I moved the thruster controls to the right joystick so only the left/right controls are on the left stick but it's still does it. I am on RetroPie 4.4.4 RA 1.7.5  - commit 8ff5a43.

**Comment by Wilstorm** [comment] 2019-01-11 23:59
To add a bit more fun information. With updates @nayslayer did there's some games with artwork masks that seem to work fine and performance is good I've tested yesterday/today. Gorf, Lunar Lander & Turbo all seem to work with multiple masking layers to give the effect of informational lighted overlays that look incredibly neat.

I wasn't able to get high enough to see Gorf or Lunar Lander change my mission/rank lighted panel from the starter light but Turbo has a speedometer with actual red "clock" style numbers and a green bar speed gauge that is probably a great example of what's possible with LED style overlays.

Lunar Lander has the neat training cadet, prime and command missions lights. It's really a nice addition to such a classic game.

**Comment by grant2258** [comment] 2019-01-13 15:59
im not having any issued with this on the a keyboard at all. Ill test on a controller and arcade panel when I get home on have access to a laptop atm

**Comment by Wilstorm** [comment] 2019-01-13 18:36
@grant2258 - I just tested and the same here. The keyboard is fine but not the controller on a left turn. I've been using a controller for so long I haven't been testing my arcade controller. I'll keep that in mind to test the keyboard also when troubleshooting as it might help.

**Comment by grant2258** [comment] 2019-01-13 18:49
I  just looked at the code the problem is the the analog code we inherited is hard coded. I have done some fixes on this but it really needs done properly. 

If you use your dpad you will be fine. 

However the analog controls do not remap (hard coded atm) the paddle control is mapped to left analog stick left and right directions. 

This is whats causing the thrust anything going through the left stick is analog as far as we are concerned for this core it not mapped through mame at all

**Comment by Wilstorm** [comment] 2019-01-13 19:32
@grant2258 - Ok, I appreciate you taking a look and will test with the d-pad. Yeah I think analog controls would be great definitely for some of the driving games I am used to just lightly tweaking the stick to steer but I noticed others when playing Ironman Offroad that aren't used to it hit the wall a lot! Should I close this for now?

**Comment by grant2258** [comment] 2019-01-13 20:07
well all you need to keep in mind is the left stick is x and y . The right right stick is z (hard coded at the moment)  most games this will work fine .  

It does need fixed up. Games like hard drivin are impossible to use atm the way the analog is hacked in atm.

**Comment by Wilstorm** [comment] 2019-01-14 01:09
@grant2258 - I mapped left/right to d-pad and up/down to d-pad also and abort to the right trigger. I was able to land on several 5x pads. I found it easier to keep my fingers on the d-pad exclusively versus the d-pad and the right stick.

AdvMAME has the same exact issue. If you turn left it fires 🔥 the thrusters. 

The lighted "LED" overlay works great in Lunat Lander and is really cool but AdvMAME it does not work.

Hard Drivin'....yeah! ;)

**Comment by grant2258** [comment] 2019-01-14 13:05
@Wilstorm its slightly off topic for here but AdvMAME should work properly if you set up,down,left right to the l analog stick. I should be there by default anyway unless it was changed.

Thats where the first problem is for our mame its set to digital hat which isint technically wrong it just means analog isint mapped to up,down,left right its only hard coded when analog inputs are use to digital controls wont work with the lstick since you cant map it and the rstick map i done for you it treated as digital

**Comment by Wilstorm** [comment] 2019-01-16 16:15
@grant2258 - I will close this for now and thank you for taking a look and the tips on how to work around it. Now it's fully playable whereas before it was to hard to land the shuttle.

**Comment by arcadez** [comment] 2019-03-30 14:46
They changed up the inputs some time after MAME78..........

0.114u4: Aaron Giles fixed Lunar Lander controls to be buttons not joysticks.
0.112u3: Derrick Renaud fixed thrust control in Lunar Lander. The way the DAC/counter circuit always trys to self center at the voltage derived from the thrust control, I don't think it ever expected to get to 0xff. We can not emulate the external DAC circuit exactly, so changing the range to 0xfe seems to solve the problem.

**Comment by arcadez** [comment] 2019-05-11 21:58
Ok i've finally got around to this, the changes from later MAME just switch turning left/right from
the analog joystick to buttons A/B thrust is still up and down on the paddle is this what was wanted..???

**Comment by grant2258** [comment] 2019-05-12 00:15
the biggest issue here is IPT_PADDLE_V  is set to left and right

https://github.com/libretro/mame2003-libretro/blob/9d38610d536253b6df0836b38bcfe2fb4e138ecb/src/inptport.c#L661-L662

it would be better changing it to  IPT_PADDLE_V 

https://github.com/libretro/mame2003-libretro/blob/9d38610d536253b6df0836b38bcfe2fb4e138ecb/src/inptport.c#L678-L679

no analog pedals are mapped in this core the pedals could be mapped to lr and rt for gamepads though if you wanted to do that.

**Comment by arcadez** [comment] 2019-05-13 22:36
I dont fancy a corewide input rewrite for one game, i should have read @Wilstorm last comments
it seems he found a workaround and can play the game well enough, so i'll close this down once
again

**Closed by arcadez** 2019-05-13 22:36 UTC
Labels: PRs welcome, bounty welcome!
