### ISSUE TITLE
Analog sticks on gamepad no longer being detected

### ISSUE THREAD

**Issue by tribunal88** [libretro/mame2003-plus-libretro#1544] opened 2023-01-27 05:50 UTC
I'm building a new retropie system and I just installed RetroPie 4.8 this afternoon on an RPi4 using 8bitdo gamepads. When I added the lr-mame2003-plus emulator (install from binaries), I discovered that while the d-pad works fine...

1) The analog sticks were unresponsive in games
2) When I opened the menu to remap controls within the game, it didn't detect input from the analog sticks (though the stick buttons were still detected and could be mapped). 

After a lot of frustration. I copied the binaries from the RetroPie I build last August (same models for hardware and gamepads), over to the new system. When I launched the games, everything worked as expected.

The package that works is the following:
pkg_date="2022-07-29T09:51:03+01:00"
pkg_repo_commit="b535de43557659a333d5f4aacd6806aa9827776b"

The one that isn't working is:
pkg_date="2023-01-26T16:43:41+00:00"
pkg_repo_commit="3ed410ea733ec6497837a3e13b96bf9e74b0babf"

**Comment by mahoneyt944** [comment] 2023-01-27 12:22
Have you remapped anything in the mame menu? If your analog sticks are responsive in RetroArch but not in the core than you likely need to map your analog sticks in the mame menu.

**Comment by mahoneyt944** [comment] 2023-01-27 12:32
You can also verify some settings in Retroarch
Load a game. Enter the RetroArch menu, goto main menu-> quick menu-> controls-> port1 controls.

Device type = "retropad"
Analog to digital type = "none".

Then in RetroArch goto:
settings-> input-> port1 controls-> analog to digital type -> none.

**Comment by mahoneyt944** [comment] 2023-01-27 12:47
Also I would recommend installing mame2003-plus from source, while this takes about 25mins to complete on a pi. It ensures you have to most up to date version.

**Comment by tribunal88** [comment] 2023-01-27 13:00
Yes. All the retroarch settings are good and as you describe. Indeed, the analog sticks are responsive in retroarch menus. The meme menu correctly opens by pressing RP1 analog button, and the current setttings are mapped as in your screenshots. However, the axis movements on both sticks are unresponsive in game, and if I remap a binding in the mame menu (as you are showing in the screenshot) nothing happens when I move the analog stick in any direction. Pressing a button (even the analog stick button) will register a remap. It's like the axis on the sticks is not getting picked up. 

The analog sticks are working in all other emulators, and that swapping out the binaries (and not any of the configuration files in /opt/retropie/configs/* or ./roms/arcade/mame2003-plus) from the package back in July fixes the issues leads me to think this is something in the code itself.

**Comment by mahoneyt944** [comment] 2023-01-27 14:34
Can you screen shot a remap with the analog stick in the mame menu?

**Comment by tribunal88** [comment] 2023-01-27 15:29
Here are several screenshots

Here's the basic config of the retroarch gamepad
![01_retroarch1](https://user-images.githubusercontent.com/18648606/215122070-6a53daf1-079a-4d80-855d-0613b614a7a4.jpg)

Here are the assignments of the analog sticks (note default)
![02_retroach2](https://user-images.githubusercontent.com/18648606/215122069-6044b5e3-fa2b-4724-92a4-7992972e11ed.jpg)

Here  is the mame menu input mapping screen showing default mappings
![03_mamemenu1](https://user-images.githubusercontent.com/18648606/215122067-38e616c5-78c5-4e6e-81c7-6d38fe4b20b4.jpg)

Here is me pressing forward on the analog stick without it registering
![04_mamemenu2](https://user-images.githubusercontent.com/18648606/215122062-0c9b5509-b117-4585-97b8-6dce4cc4444e.jpg)

Now I press the analog stick button and it registers the assignment
![05_mamemenu3](https://user-images.githubusercontent.com/18648606/215122060-84862060-0367-49ed-b1da-05011ad9dd2e.jpg)

And if I swap out the /opt/retropie/libretrocores/lr-mame2003-plus directory with the one from the working RetroPie (which I build last August), I am able to map with the sticks as expected.

**Comment by mahoneyt944** [comment] 2023-01-27 16:39
@MistyDreams  That's odd mine works on Android. Driver issue?
![Screenshot_20230127-113820](https://user-images.githubusercontent.com/49591133/215142798-76457125-8628-4056-8e80-34e3138c9f0d.png)

**Comment by mahoneyt944** [comment] 2023-01-27 16:41
@tribunal88 shouldn't be too hard once the issue is isolated, oddly this isn't effecting all platforms.

**Comment by mahoneyt944** [comment] 2023-01-27 16:47
Maybe an issue with old RA that pie uses and the new core? I'm on the current stable ra build

**Comment by mahoneyt944** [comment] 2023-01-27 16:52
What build of RA?

**Comment by mahoneyt944** [comment] 2023-01-27 17:01
Works for me on ra 1.14.0 Android with current mame2003+ core.

I'll dig out my pi when I get home and try to update it and see where that gets me.

@tribunal88 just to confirm, did you try to reconfigure your controller in Emulation station?

**Comment by mahoneyt944** [comment] 2023-01-27 17:09
Just saw this, any chance you're also using a 8bitdo controller?
https://retropie.org.uk/forum/topic/33829/controller-working-in-emulationstation-but-not-in-retroarch

**Comment by mahoneyt944** [comment] 2023-01-27 17:12
Well I'll be home in about 3.5 hrs from now and I'll test my rpi3. Can't imagine what the issue is.

**Comment by mahoneyt944** [comment] 2023-01-27 17:15
It definitely worked before because I use it to play food fight on my pi. Something effecting the Linux builds? Hasn't really been input updates in a while.

**Comment by mahoneyt944** [comment] 2023-01-27 17:21
Maybe try a build without the c89 standard enabled?

**Comment by mahoneyt944** [comment] 2023-01-27 17:43
Try logging the analog input, is mame even seeing it?

**Comment by tribunal88** [comment] 2023-01-27 18:24
@mahoneyt944  - I tried a number of things: reconfigured emulation station, reconfigured retroarch, fresh resintall. To your other question, I am using an 8bitdo controller, but its the Pro 2, not the Zero 2, and the gamepads are working fine with all other emulators.

@MistyDreams  - appreciate the early access. I'm an IT admin by trade so I'm curious what the root cause was.

Cheers, all!

**Comment by mahoneyt944** [comment] 2023-01-27 18:58
@MistyDreams are you sure it's not the use of round which is the issue? It returns as an int so that probably doesn't need to be there. That map function seems to "- 0" a lot. Since these are static it basically boils down to `128*(coord/32767)`

**Comment by mahoneyt944** [comment] 2023-01-27 19:35
I'm just not seeing what the fix is in your map function from what's there now they both seem to give me the same results. What coordinate trips this up? The only difference I see is that the round function returns a double and rescale_analog is suppose to return an int which might cause an issue.

Sample
Value or coordinate = 1008
Start1 = 0
Stop1 = 32767
Start2 = 0
Stop2 = 128

Current
```
Scale_factor = 128/32767
Return scale_factor * 1008
3.93762016663
```

Your PR
```
0 + (128 - 0) * ((1008 - 0) / (32767-0))
3.93762016663
```

**Comment by mahoneyt944** [comment] 2023-01-27 19:48
That's why I thought maybe we need this
`return (int)round(scale_factor * libretro_coordinate);`

**Comment by mahoneyt944** [comment] 2023-01-27 20:13
Does this work for you?
return MAME_ANALOG_MAX * (libretro_coordinate / LIBRETRO_ANALOG_MAX)

**Comment by mahoneyt944** [comment] 2023-01-27 21:24
How about this
```
int rescale_analog(int libretro_coordinate)
{
  float rescale = (float)MAME_ANALOG_MAX * ( (float)libretro_coordinate / (float)LIBRETRO_ANALOG_MAX);

  if (libretro_coordinate == LIBRETRO_ANALOG_MIN) return 0;

  return (int)rescale;
}
```

**Comment by mahoneyt944** [comment] 2023-01-27 21:49
I'm open to other ideas but I committed this, https://github.com/libretro/mame2003-plus-libretro/commit/bf4f26f6fd671a4a883a10bcec00790d543d95e3 does this fix the issue? We can open a new issue for deadzone if we want to look into that also.

**Comment by mahoneyt944** [comment] 2023-01-27 22:06
@tribunal88 please update the core from source and confirm it's working for you.

**Comment by tribunal88** [comment] 2023-01-27 22:57
"Installed from source" and it's working as far as I can tell. Did a bunch of testing on both sticks. 

Cheers!

**Comment by mahoneyt944** [comment] 2023-01-27 23:28
Good news.

**Closed** 2023-01-28 00:36 UTC
