### ISSUE TITLE
1943kai/1943mii flip screen causes graphical glitches

### ISSUE THREAD

**Issue by gomisensei** [libretro/mame2003-plus-libretro#820] opened 2020-07-05 02:08 UTC
In first stage of both clones, if dip switch "flip screen" is set to on, floating ships are on opposite side of where they are without screen flip, but the gun emplacements that should be on the ships are in the water on the other side of the screen.  Behavior is correct in fb neo emulator.  The scrolling also seems weird, like the shups are flying backwards.
![1943mii](https://user-images.githubusercontent.com/2192653/86523987-6a06f980-be29-11ea-867f-44f3ebc01f2b.png)

The reason i had flipped screen is that turning on TATE rotates the games left, instead of right.  is there a way to set which direction TATE mode rotates?

![1943mii](https://user-images.githubusercontent.com/2192653/86524008-a9cde100-be29-11ea-876c-3f1ec5b29b26.png)

**Comment by gomisensei** [comment] 2020-07-05 02:28
also, baseline mame (0.221) shows that dip switch as cabinet type, with "upright/cocktail" as the options, but even enabling it doesn't cause the same issue as in 2003-plus.

**Comment by arcadez2003** [comment] 2020-07-05 21:15
You mentioned two versions what about 1943 does it have the same issues.?? im thinking our ole driver does not support
screen flipping in the video code hence the issue, maybe it was added later in the MAME dev cycle.?? or the problem is
a totally unrelated matter.??

Anyway i'll check the MAME WIP for this driver sometime

**Comment by gomisensei** [comment] 2020-07-05 21:56
1943 has the same issue, 1942 dip switches don't have screen flipping, but cocktail mode, and it seems to work as intended, probably because it is turn based, while the newer games are simultaneous. According to documentation, that dispswitch should be "cabinet type" and not "screen flipping".  On a related note, can we switch the direction for TATE mode to the standard (90 degree) rotation, instead of 270? or allow for all 4 directions...

**Comment by arcadez2003** [comment] 2020-07-05 22:00
Yeah i get the same issues, it's a problem with the MAME video code for the clones i would think, maybe this is the fix.......

0.88u1: Curt Coder cleaned up the driver, converted 1943 to use tilemaps, merged memory maps and fixed inputs/dips based on manuals. Changed description to '1943 Kai: Midway Kaisen (Japan)'.

Certainly there is no mention directly in the MAME WIP about a fix for screen flipping in either of the clones, do me a favour
if you can grab one of the advance MAME builds available for the Rpi one based on MAME106 would be best, try 1943kai
using that core and see if the problems are sorted or not.

If they are sorted then i'll know the above changes from MAME88 will be what are needed here to fix this.

**Comment by gomisensei** [comment] 2020-07-05 22:09
behavior in advmame is correct

**Comment by arcadez2003** [comment] 2020-07-05 22:16
Ok looks like i have a job to do :)

**Comment by gomisensei** [comment] 2020-07-05 22:24
mame2010 correct also, but it seems to have other issues

**Comment by gomisensei** [comment] 2020-07-05 22:29
> Yeah i get the same issues, it's a problem with the MAME video code for the clones i would think, maybe this is the fix.......
> 
> 0.88u1: Curt Coder cleaned up the driver, converted 1943 to use tilemaps, merged memory maps and fixed inputs/dips based on manuals. Changed description to '1943 Kai: Midway Kaisen (Japan)'.
> 
> Certainly there is no mention directly in the MAME WIP about a fix for screen flipping in either of the clones, do me a favour
> if you can grab one of the advance MAME builds available for the Rpi one based on MAME106 would be best, try 1943kai
> using that core and see if the problems are sorted or not.
> 
> If they are sorted then i'll know the above changes from MAME88 will be what are needed here to fix this.

most likely it's the tilemaps, as the background layer just seems to be going in the wrong direction...

Heh, you added 1943 part 2 to this core on my request about 2 years ago.  Thanks for the spurt of work while retired...

**Comment by arcadez2003** [comment] 2020-07-07 23:06
Right this didn't go well the changes from MAME88 were just a drop in, but in my MAME84 and 72 test cores all the 1943
games now run at 1fps totally unplayable, i suspect the tilemapping code in this and my test cores is incorrect, some further
investigation will be required.

I'll don my sherlock hat and pick up my spyglass sometime down the road but at the moment i dont have the time.

**Comment by arcadez2003** [comment] 2020-08-28 13:53
I've decided to just leave this as if we start updating the tilemap code to MAME88 this will affect more or less every game
in this core and could end up breaking far more than we fix, and this will only create more work down the road to put
everything right again.

**Closed by arcadez2003** 2020-08-28 13:53 UTC
