### ISSUE TITLE
Bubble Bobble `bublbobr` (MAME 2003 Full Non-merged Reference Set) no longer works

### ISSUE THREAD

**Issue by SapphireTactician** [libretro/mame2003-plus-libretro#151] opened 2018-04-26 16:48 UTC
### Description

"Bubble Bobble w/ Mode Select" (*rom name: `bublbobr`*) from the MAME 2003 Full Non-merged Reference Set no longer works on the MAME 2003 Plus core. It still works in the regular MAME 2003 core however.

When using the verbose option on RetroArch with the MAME 2003 Plus core, the following problem is revealed:

```
[libretro INFO] Found game: bublbobr [bublbobr].
[INFO] Environ SYSTEM_DIRECTORY: "/home/drew/.config/retroarch/system".
[INFO] Environ SET_ROTATION: 0
a78-01.17    NOT FOUND
ERROR: required files are missing, the game cannot be run.
[ERROR] Failed to load content.
```

It should be noted that file `a78-01.17` is not part of `bublbobr` for the MAME 2003 Reference Set; it is present however in the MAME 2010 Reference Set version.

-----

### Expected behavior

Game should run normally and be compatible with the 2003 version of `bublbobr`, and later versions if desireable.

-----

### Actual behavior

Fails to load due to rom missing file `a78-01.17` which is not required by MAME 2003.

-----

### Steps to reproduce the bug

* Load the MAME 2003 Full Non-merged Reference Set version of `bublbobr`
* Select the `Arcade (MAME 2003 Plus)` core
* Game won't play

-----

### Logs:

**Relevant `--Verbose` Terminal Output:**

```
[libretro INFO] Found game: bublbobr [bublbobr].
[INFO] Environ SYSTEM_DIRECTORY: "/home/drew/.config/retroarch/system".
[INFO] Environ SET_ROTATION: 0
a78-01.17    NOT FOUND
ERROR: required files are missing, the game cannot be run.
[ERROR] Failed to load content.
```

-----

### Bisect Results:

After extensive, although not exhaustive (*takes too long to compile every commit along the way*), testing, the last known working commit seems to be 9d82c48 . Failure is observed as early as commit 36954d6 , however that may not be the earliest instance it fails.

It is very important to note that when commit 9d82c48 is compiled, the core's filename ends up being `mame2003_libretro.so` instead of `mame2003_plus_libretro.so`

This has me severely worried about bug regressions involving various games we fixed as of that very important commit.

-----

### Version/Commit Info:

- **RetroArch Version:** 1.7.2 f0e057c8d0
- **MAME 2003 Plus core commit version:** 1a22bc7

### Environment information

- OS: Debian 9 (*Stretch*) Stable x86_64
- Compiler: gcc 3.6.0 64-bit

**Comment by Wilstorm** [comment] 2018-04-26 17:41
I just played this a few days ago on regular lr-mame2003 and it did run fine. I was just adding a comment as I see you mentioned it above.

**Comment by arcadez** [comment] 2018-04-26 18:14
Your rom is incorrect it's missing the MCU dump which is now required for this core
or you'll get a load error.....

ROM_REGION( 0x10000, REGION_CPU4, 0 )	/* 64k for the MCU */
ROM_LOAD( "a78-01.17",    0xf000, 0x1000, CRC(b1bfb53d) SHA1(31b8f31acd3aa394acd80db362774749842e1285) )

**Comment by arcadez** [comment] 2018-04-26 18:35
I updated this driver adding support for the proper MCU dump for Bubble Bobble, 
this means the original rom from mame2003 is not compatable in this core, unless
you happen to have "a78-01.17" otherwise you'll get a romload error.........

This is the commit where i made the changes

https://github.com/libretro/mame2003-plus-libretro/commit/8a025f37d83aff53cfba308cb2e6dcab0c61e614#diff-3124aa496f398b50111d1d5d5674490e

**Comment by arcadez** [comment] 2018-04-26 19:02
Alright on spec i grabbed both Bubble Bobble and Bubble Bobble With Mode Select
and both games work for me, the code is the exact same in this and my test core so
i can only assume if you have the correct rom versions these games should work in
mame2003-plus

Regards

**Comment by SapphireTactician** [comment] 2018-04-26 19:10
Should we really be breaking compatibility with mame2003 romsets? I thought the goal is to be literally 2003 Plus.

Or is there a newer revision of the 2003 reference set than v3 / February 2018?

**Comment by arcadez** [comment] 2018-04-26 19:27
Some people just dont like rom changes or is the work they then have to put in to update
their romsets i never can tell, i try to keep this to a minmium but for certain games to work
or have full sound this sometimes means the roms have to change simple as.

The whole pooint of this core is support new games or fix up broken ones or add sound support
where it was lacking, for this to happen the romsets have to be altered  @SapphireTactician you 
asked me earlier to update the esd16.c  driver the roms will likely change in the process or should
i just scrap the driver update for those that are rom change averse :)

**Comment by grant2258** [comment] 2018-04-26 19:33
@arcadez personally i dont really care if romsets change maybe we should rename this core and take the name association away unless the merge is the goal

**Comment by arcadez** [comment] 2018-04-26 19:45
It'll never be merged too many folks dont want to see that happen, so yeah maybe for the best
to totally remove any connection namewise to mame2003, we could always revert back to
using MAME78 or you guys might come with something more imaginative :)

**Comment by grant2258** [comment] 2018-04-26 19:49
mame_arcadez(mame078 with updated drivers and added roms) :D will look good in in the retroarch desc

**Comment by grant2258** [comment] 2018-04-26 19:53
haha it looks sweet to me

**Comment by grant2258** [comment] 2018-04-26 19:56
@arcadez is your port for the original xbox or xbo360 I have two two moded xbox360s can rememver what glitch chips i put in them though was a while ago

**Comment by arcadez** [comment] 2018-04-26 19:59
Oh i didn't port em buddy thats above my paygrade what i did was similar to here take
the original port and update it, i have four on the go just now FBL which is an FBA port
to the original xbox.

And MAME wise i have 72 and 84 for the xbox and i just updated MAME72 on the xbox360

**Comment by grant2258** [comment] 2018-04-26 20:02
how do i grab it and install it arcadez i think that might be a nice alternative for me!

**Comment by arcadez** [comment] 2018-04-26 20:03
which ones you after..??

**Comment by grant2258** [comment] 2018-04-26 20:04
72 and 84 never ever used alpha at all to be honest

**Comment by arcadez** [comment] 2018-04-26 20:11
You'll only need MAME 84 really as it supports everything that MAME72 does however
MAME72 does have a slight edge with performance and inputs for some games.
FBL will support certain games the above emulators dont and play em better.

Anyway grab MAMEoXtras from here follow the install guide and you should be
up and running pretty quickly i can help ya out here and there should ya get stuck ;)

http://www.emuxtras.net/forum/viewtopic.php?f=189&t=6072

**Comment by grant2258** [comment] 2018-04-26 20:15
sweet thanks mate you probably wont see me for a while time to get the xbox and maming on the big screen is appreciated. What gui you using for the the xbox360 is it still aurora we are using its been a while

**Comment by Wilstorm** [comment] 2018-04-26 20:34
> This required removing the cover from the chip, taking photographs of it under a microscope, and manually decoding the contents of the ROM bit by bit.

That's incredible how this guy did it.

@SapphireTactician - All you need to do is add a single extra ROM to your existing set and it will work in either emulator. Just don't process it through lr-mame2003 DAT or it will remove it *but* it will process fine with the mame2003_plus reference DAT. 

Actually mame2003_plus has the better flexibility as it's ROM will work in either but the lr-mame2003 ROM will only work in lr-mame2003. MAME doesn't care about extraneous ROMs in a set. As far as it knows it might be another clone or parent ROM from a merge set.

I kind of track changed ROMs from lr-mame2003 to mame2003_plus_libretro and there's already roughly 30 ROMs that have changed from the original lr-mame2003 reference set and about 90 new ROMs added. I can get an exact list of ROM names that have changed if you want. 

Reading Arcadez added information posted above it sounds like there is an incredible amount of fixes that were missing from the handwritten bootleg ROM vs. the correct accurate dump that make it worth the new accuracy of game play implemented alone.

**Comment by arcadez** [comment] 2018-04-26 20:38
@Wilstorm on a slow day with nothing much on the cards you might wanna checl out this
site which details how the recent MCU dumps for MAME were done.........

http://caps0ff.blogspot.co.uk/

**Comment by Wilstorm** [comment] 2018-04-26 20:46
@arcadez - I just took a quick peek thanks that's perfect. I actually find that type of information interesting!

**Comment by SapphireTactician** [comment] 2018-04-26 20:58
@arcadez Oh, I get it now. I was operating under the assumption that the name had meant that it was designed to play everything from the MAME2003 set as-is **PLUS** additional games backported from later romsets so that we have the speed of 2003 but with a much larger library. I feel like a lot of users may be operating under the same assumption as I and will be confused when the rom doesn't work as-is without the additional file.

As for the newly required file, should I import it from the 2010 version? Or should I simply use the 2010 reference set version of the game instead on this core? Please advise.

My only adversion is that it throws a curveball that users from the "it just works" camp like myself don't exactly know how to handle correctly. Is there no way for the driver to handle both versions?

On a sidenote, reading that history of the ROM gave me an even deeper appreciation for a game that I already deeply appreciate.

**Comment by arcadez** [comment] 2018-04-26 21:15
@SapphireTactician as @Wilstorm said you can just drop the extra rom for the MCU into
both bubbbobr.zip and bublbobr1.zip and they'll both work across both cores.

The parent rom bubblbobl.zip will cause problems as there was a redump of the two main
CPU roms and they have different CRC.s but are named exactly the same so you cant just
create a dual purpose rom for that one i dont think..?? try it and see at anyrate.

**Comment by Wilstorm** [comment] 2018-04-26 21:19
If you use a ROM manager like ClrMamePro the mame2003_plus DAT will process it fine *or* even simpler just unzip the 2010 ROM set, move the file ```a78-01.17``` to the desktop or wherever. Then add it to these 3 sets:

```
"Bubble Bobble" bublbobl.zip
"Bubble Bobble (US with mode select)" bublbobr.zip
"Bubble Bobble (US)" bubbobr1.zip
```

Then your sets will work in either emulator.

To get the new accurate version Arcadez implemented you would have to ask the lr-mame2003 folks to add the code updates to their version.

There's a small caveat that I have no idea what lr-mame2003 does for changes or additions. I'll try to explain. When the "trio" here setup mame2003_plus these guys added support to generate a DAT on the fly, so new reference set changes are immediately available to the user to process and update their ROM sets. That's a big deal.

When they make a change to lr-mame2003 I have no idea if anyone updates a DAT or if it's word of mouth a new more accurate version works in the emulator or how updated ROMs are made available to the end users.

I think your assumption is mostly correct. There's roughly 5,000 ROM sets and roughly 4,810 or so are 100% bit-for-bit accurate. Roughly 30 have been modified from the original lr-mame2003 set and 90 or so new additions that aren't available in lr-mame2003.

I can give you a list of changed ROM set names but not what actual ROMs in the set have changed but that would only require you to open them with Winzip or something to take a look. I keep a shell version program that gives me the CRC/SHA1/MD5 of a file by right clicking and viewing the properties of a file. Also WinMerge is a great way to compare files. If you compare zips it needs to be Torrentzipped or some other utility that will create a consistent hash value.

**Comment by Wilstorm** [comment] 2018-04-26 21:31
>The parent rom bubblbobl.zip will cause problems as there was a redump of the two main
CPU roms and they have different CRC.s but are named exactly the same so you cant just
create a dual purpose rom for that one i dont think..??

Yeah that might be a challenge. Ok so the parent ROM would be different.

What I've been doing is keeping a perfect lr-mame2003 reference set. Then I create a DAT of just the differences (at a ROM set level) compared to mame2003_plus. Then when I need to create a mame2003_plus set I copy them right over the top and you instantly have a mame2003_plus set. It's a space saver of several gigs vs building the entire set.

@markwkidd - Someone already did an awesome tutorial right in the RetroPie docs. It explains things well too.

https://retropie.org.uk/docs/Validating,-Rebuilding,-and-Filtering-ROM-Collections/

**Comment by arcadez** [comment] 2018-04-26 21:41
@Wilstorm there is the possibility to just roll the main cpu roms back to what they were
for mame2003, i'd need to check the MAME Wip to see why they were redumped in the
first place, although i assume it was for good reason maybe connected to the MCU dump..??

**Comment by Wilstorm** [comment] 2018-04-26 21:46
> although i assume it was for good reason maybe connected to the MCU dump..??

Yeah that makes sense that they are connected to the new/correct ROM dump.

**Comment by arcadez** [comment] 2018-04-26 21:53
Nah sorry my mistake there was a new version dumped around MAME95 so the previous
parent became a clone, the roms are actually named different i think i need to get my
ole peepers tested.......

Bubble Bobble parent mame2003
"a78-06.51",    0x00000, 0x08000, CRC(32c8305b)
"a78-05.52",    0x10000, 0x10000, CRC(53f4bc6e)

Bubble Bobble parent mame2003-plus
"a78-06-1.51",    0x00000, 0x08000, CRC(567934b6)
"a78-05-1.52",    0x10000, 0x10000, CRC(9f8ee242)

This is your cores guys what'ya wanna do..?? i can just roll it back and use the maincpu roms
from mame2003 or keep them as they are

**Comment by grant2258** [comment] 2018-04-26 22:00
@arcadez just leave it we have a dat generator rename the core and do what we are going the only parts that need to stay the same are the osd functions to control mame from libretro there is no reason we have to be tied to the 2003 romset if we arent merging

**Comment by markwkidd** [comment] 2018-04-26 22:10
I also say keep the bugfixed versions.

**Comment by SapphireTactician** [comment] 2018-04-26 22:13
>there is no reason we have to be tied to the 2003 romset if we aren't merging.

Ummm, I probably don't have any say in this as I'm just a tester, but I'd really really like to NOT have to throw out / overhaul an entire romset. Especially because there is no reference set for 2003 Plus, meaning I'd have to hack and piecemeal who knows how many roms if the 2003 set gets completely divorced. Furthermore ClrMamePro doesn't run on Linux unless I want to deal with WINE (*which really I don't - I want to move away from Windows, not cater to it with a compatibility layer*). On that note, is there a Linux alternative to ClrMamePro?

That said all, while I'm all for bug fixes and extra compatibility, it'd be very very much appreciated to be, for lack of better words, backwards compatible with the 2003 romset.

**Comment by Wilstorm** [comment] 2018-04-26 22:15
@arcadez - But your one of the founding fathers like good ole George Washington right on Mt. Rushmore. The first in line.

So does rolling back mean loosing the new accurate version you implemented? If so I would opt to keep the new version.

**Comment by arcadez** [comment] 2018-04-26 22:16
It's not a bugfix per say more a new version was dumped.....

0.94u3: Tormod Tjaberg added Bubble Bobble (newer set). Renamed (bublbobl) to (bublbob1).

The code wasn't originally mine so what the dev must have done is used the new parent
above without then supporting the new clone BritneysPAIRS was known for his hacky
shortcuty methods :)

Thats how i missed it, there's nothing to stop us just keeping the original parent from mame2003 
but it will still support the new protection MCU.

**Comment by Wilstorm** [comment] 2018-04-26 22:33
> specially because there is no reference set for 2003 Plus, 

@SapphireTactician - You actually do have a reference set, but even better, it's dynamic.

You're thinking of traditional MAME that set (MAME 0.78) is static for all of time for eternity. Each new release is static 0.79, 0.80, etc. What Plus is doing is doing different is it started with 0.78 as it's base and is in a perpetual state of updates. It will never have a static set in the traditional sense.

This is jut my opinion but a ROM manager tool is a must. If not you would need to track every commit hand edit your ROMs which sounds crazy to me. From week to week the set is stale and you need to update your set to take advantage of the new ROM additions and updated accuracy like Bubble Bobble.

I know what your saying but take Bubble Bobble for example. Would you prefer the older inaccurate set just so the set works both ways or the new 100% accurate game that played exactly like the arcade.

It's a tough call but really no different than say mame2010 (also a "true" static set) or mame2014, or mame2016, etc. those emulators are static sets. mame2003_plus is not traditional in it's a dynamic set that has ROMs being added and updated vs. just working on the interface or options, etc. like these other emulators do.

>Thats how i missed it, there's nothing to stop us just keeping the original parent from mame2003
but it will still support the new protection MCU.

Wow, that's almost tempting. You can keep the same parent ROM but still have the accurate MCU only needing to add a single ROM. I think I would opt for that then.

**Comment by arcadez** [comment] 2018-04-26 23:01
Ok apart from the new MCU the parent rom for Bubble Bobble is the exact same now as
it was in mame2003

**Comment by SapphireTactician** [comment] 2018-04-26 23:04
@Wilstorm Your assessment of my thinking is 100% correct. My (*mis*)understanding was that it would be the static 2003 set but the added benefit of backports of games that weren't available to 2003, plus any fixes so long as editing roms isn't mandatory (*I feel such edits should be optional, if the user wishes to take advantage of the improved accuracy, they made, but those who can't / don't want to be bothered shouldn't be forced to*).  

Don't get me wrong, I really do appreciate things like increased accuracy, especially for games I care about, plus fixing sound and video (*as "Bonk's Adventure" `bonkadv` won't work in 2003 but works great in 2003 Plus*), but I'd like the option to be able to use the same core even if I'm happy with a rom as-is (*in other words, it should be able to use either the old parent or the patched parent, in case someone like myself is too lazy to keep patching a rom in order to keep up with a rolling release cycle, but yet still wants the other benefits the core has to offer*).

Perhaps I'm asking for too much (*in regards to the project's direction and not just this individual case*), especially given that I'm not a developer here.

**Comment by arcadez** [comment] 2018-04-26 23:24
It's done all you need to do is have the MCU rom in your bublbobl.zip and bingo it will work
across both cores.

**Comment by SapphireTactician** [comment] 2018-04-26 23:37
@arcadez When fixes / new versions of roms like this happen in the future, can it be possible to allow the old static version to still be usable as well within this core? I love new stuff, but only when any changes that require end-user action is optional.

I understand if that's not acceptable. After all, I get my original understanding of this core isn't compatible with the direction @grant2258 seems to want since merging with 2003 seems unlikely according to him. Maybe it's the fact that I'm a Debian user, but I'd like the option to continue using this amazing core along with any backports for it, but at the same time, not feel forced to patch a rom if I'm satisfied with it / can't be arsed.

**Comment by arcadez** [comment] 2018-04-26 23:53
@SapphireTactician 

At the end of the day the choice is in your hands to either take advantage of this new core understanding the direction we are taking and that you may have to update the odd rom or 
sample here and there or just stick with the original mame2003 core.

You do come across as whining a bit here keep in mind no one is forcing you or anyone
else to use this core, but be rest assured im not planning anymore significant changes to
the drivers or roms that they support infact i thought i was done until you requested
i update esd16 earlier

**Comment by arcadez** [comment] 2018-04-27 00:02
@Wilstorm your totally correct the roms change with every MAME, FBA or Raine release
their are never truely static, i hate updating roms myself but if you were to post something
to that effect over on the mameworld forums you would be told to go and do one very
quickly.

At the end of the day it's a users choice to update to the latest mame with the understanding 
that alotta stuff will have changes and you may have to put in a bit of graft to get everything
up and running or just stay on an older version bus miss out on the fixes and improvements
that come with each new release.

Take Bonze Adventure in every MAME release bar the last the game will crash on later levels
but with the new C-Chip dump that's fixed but you'll need a new rom to take advantage of this
the same dilemma rings true for users of this core or those that prefer to stick with mame2003
it's horses for courses know what i mean.

**Comment by SapphireTactician** [comment] 2018-04-27 00:08
Sorry about that, I tend to think in extremes / worst case scenarios. The way @grant2258 talked about not wanting to be "tied to 2003" left me under the impression that in the future, updates to roms could become increasingly frequent, or drastic. To be perfectly honest, my main draw to this core was the backports; I mainly just want a 2003 that can use later games since later mame cores and FBA are too slow for my target devices like the RPi.

And again, the way you said is fine, but imo I feel it should also remain backwards compatible for those who are in it for just the increased library.

**Comment by grant2258** [comment] 2018-04-27 09:47
@SapphireTactician i said there is no need to be tied to the mame2003 romset if we arent merging as long as we keep the mame core (libretro) functionality the same between both. so fixes can apply to both platforms. Obviously we will try to keep the base romset working but its not always possible

**Comment by dankcushions** [comment] 2018-04-27 10:27
> Especially because there is no reference set for 2003 Plus

the reason there is a reference set for mame2003 is because it became so popular. there wasn't one when i started working on it - you had to really hunt!

i see no reason why a similar set wouldn't be circulated by the scene for plus, in time (and once we have a sort of stable romset).

**Comment by grant2258** [comment] 2018-04-27 10:36
@SapphireTactician im sure i seen some where on the retropie forums cant remember where someone made a clrmame like utility for linux for mame

**Comment by grant2258** [comment] 2018-04-27 10:43
@SapphireTactician found it https://retropie.org.uk/forum/topic/15233/mame-set-rebuilder

**Comment by arcadez** [comment] 2018-04-27 13:52
Ok i kinda feel i let the tail wag the dog last night when i reverted the Bubble Bobble parent set
back to MAME78, the problem with this is although it makes it easier for people to have combined
romsets across the two mame2003 cores it actually makes it more confusing for the average joe
to download the correct rom for use in THIS core.

The dev's who have contributed to this core have knocked their pans in to better the codebase
and in turn the end user experience we seek to take the mame2003 core in a slightly different
direction we're not reinventing the wheel from scratch here.

i would like to remind folks that this core is in no way compulsory nor is there is any gun at your
head forcing you to use it, all we ask is that you accept in some instances the roms and some GUI
features will be different in this core than in mame2003 and if you cannot this then simply 
mame2003-plus is not for you!!

**Comment by arcadez** [comment] 2018-04-27 14:01
In light of the above i am restoring the bubble bobble parent from MAME107 however
i will also be adding support for the missing rom so we now have the full proper parent
clone relationship for all the sets.

I dont really think we should take users of the other core into account whatsoever with
regards to mame2003-plus if they want to create a rom off their own backs that will
function across both cores then it can easily be done

**Comment by Wilstorm** [comment] 2018-04-27 15:17
I don't completely disagree but I don't completely agree either. If it was me and it required no extra work to keep ROM compatibility across 2 cores I would do so. If it required a bunch of work to do so then probably not.

Having a 100% compatibility is a nice bonus but let's face it it's not why we use these older cores. I mean for current perfection emulation? Not really.

I thought you're original suggestion was excellent. It allowed ROM compatibility across both cores with the best part incorporating the MCU decryption ROM. It never hurts to have a bit of "inter-departmental" corporation between cores. It builds bridges and lays foundations for future joint projects or maybe you just need some help with something or someone to bounce ideas off of or just to chat.

I do know plenty of folks that don't give a rats ass about what others think or care and if they get help or not. They could live out the rest of their days in the boondocks and be happy.

It just seems like you reverted your work more to make a point than for the practicality of it.

People ca *not* easily do what you devs do because if we could then we would do it ourselves. Well at least I know I would. I guess I think similar when it comes to switches, firewalls or routers, SANs, doing some subnetting, VLANs, routing protocols like OSPF, RIP, etc. it can easily be done so get to it. Well shoot because that's what I've been doing for 26-27 years.

Now before you bring your hammer out. I am not complaining but I always feel a need to share when someone shares even when I take an ass wiping for it. I'm not saying I look for fights but I like to hear/share all points of view. I know you stated you don't work "politics" and I believe it. Also said no one has a gun to my chest and that's true. I will be alright either way with or without this core but I hoping for the former.

You remind me a bit of a gruff guy that has a good heart. When you basically told them to piss off on the RetroPie forums I never thought for a minute you were a cruel mean guy. In fact banning you was a poor decision as far as I am concerned. You did nothing wrong as far as I can tell. Not even today do I understand why and I read your posts right up to the even more than once. Ok I could go on for a page on that alone but forum moderation shouldn't be conducted in that manner. Water under the bridge.

In your words it does feel a bit Draconian as in harsh point of view to completely turn your back on the lr-mame2003 core. I think there's certain aspects that you should consider or take into account pertaining to lr-mame2003. I think some of the work your doing is making its way up the tree and to other cores. You guys are pioneering some ideas and implementations that seem like a good fit for Libretro and Retroarch. You have a good thing going and going completely rogue might not be the best idea but I respect and support any decision the core team makes because quite frankly I have zero control over it anyway and might as well sit back to enjoy the ride! ;)

Honestly I just use the damn DAT and it works fine when building sets ;)

**Comment by SapphireTactician** [comment] 2018-04-27 15:29
Why is this reopened if it's been made abundantly clear that the issue I opened won't be addressed? Feels like a slap in the face to me. Just leave it closed and slap a `Won't Fix` label and be done with it?

Also, there is a way we can have both the fixes / improved accuracy and user convenience, or at least I think so. If we're not going to allow backwards compatibility with certain lr-mame2003 roms (*although I really don't see why that would be such a herculean task, simply have a check for if the extra / correct file(s) is present or not and then emulate appropriately*), then why not keep it user friendly and just say use the MAME 2010 reference version of the game instead, that way users don't have to piecemeal, reverify / rebuild stuff. The current method is honestly user-hostile for legitimate reason imo.

**Comment by grant2258** [comment] 2018-04-27 15:30
@SapphireTactician i gave you a link to a clrmame like utility for mame tou can build sets there shouldnt be a issue you cant use clrmame anymore

**Comment by Wilstorm** [comment] 2018-04-27 15:39
Sorry Grant I think I was trying to make a completely different point then @SapphireTactician. I would never insinuate for you fix something because I was raised old school as get your ass in there and do something about it if you don't like it.

I think Sapphire is telling you he doesn't think it should be a Herculean task which I have no idea. It might be but honestly I don't enough about the code to speak intelligently about it.

I feel he fails to understand the only way to keep it fully cross-platform compatible is leave the lr-mame2003 set completely alone and only add new ROMs and well that's just not practical. You would need to start naming ROMs odd names and adding all this extra code so as not to disturb the lr-mame2003 reference set.

**Comment by SapphireTactician** [comment] 2018-04-27 15:44
@Wilstorm Depends on how it can implemented, I'm hoping it can boil down to a simple branch where it performs a check and then emulates either the old version or the fix accordingly based on if the needed files are present or not.

>I feel he fails to understand the only way to keep it fully cross-platform compatible is leave the lr-mame2003 set completely alone and only add new ROMs and well that's just not practical. You would need to start naming ROMs odd names and adding all this extra code so as not to disturb the lr-mame2003 reference set.

I understand that concern and I'm not suggesting something as draconian as 2003 or GTFO. Would I like to see 2003 roms still supported as-is? Yes. But if we insist on having some newer stuff, then why not just backport the 2010 / MAME 0.139 version? Then instead of having to frankenstein 2003 romsets, we can say use the 2010 version for the following games. I think that would be a very user-friendly compromise.

**Comment by grant2258** [comment] 2018-04-27 15:47
@SapphireTactician you cant just take a driver from mame2010 a pop it into mame2003 the tilemap system and other things are different its not just a matter of pasting code. You should post a message on the mame board to tell the to make the latest mame compatible with mame2010 as well while your at it cause that is basically what your asking arcadez to do

**Comment by markwkidd** [comment] 2018-04-27 15:59
I think it needs to be as easy as possible for people to rebuild their
romsets with a tool. We should for example make sure what other collection
people can rebuild from -- is MAME 0.78 plus MAME 0.139 enough? MAME 0.78
plus rollback?

I will look into this as soon as possible. Rebuilding romsets is something
I think we all want to minimize, but it's an everyday part of mame
emulation outside of these historical cores. It's amazing how little these
romsets are changing for such dramatic increases in functionality.

**Comment by SapphireTactician** [comment] 2018-04-27 16:21
So I guess everyone here wants a written, formal, apology for suggesting a user-friendly MAME that has the performance of one but the compatibility / fixes of another. Then fine, I get it. I'm sorry. I'll just be a simple little mindless tester and keep my opinions to myself. If something breaks due to missing files, I won't report it anymore. A simple, "Won't Fix" label will suffice.

It's better than me getting grief for it and then having an issue I voluntarily closed, acknowledging it won't be fixed, reopened just to slap me in the face.

**Comment by Wilstorm** [comment] 2018-04-27 16:33
>  I'll just be a simple little mindless tester and keep my opinions to myself. If something breaks due to missing files, I won't report it anymore. A simple, "Won't Fix" label will suffice.

This isn't right either and don't apologize. Testers are important. They need to hear about what's broken. That is what I am too!

You may make suggestions of ANY kind and doing so politely is always appreciated. Then if the devs feel like it's a reasonable contribution to the project they will implement it. At the end of the day they do have complete autonomy and for good reason. They are volunteering hundreds of man hours of their time out of passion for something they love.

**Comment by Wilstorm** [comment] 2018-04-27 16:46
@markwkidd - Yeah I think fixed is fine. I do think a reasonable expectation needs to be decided upon. Whether or not a learning a tool is necessary for this core, well better yet just follow the tutorial at RetroPie. Plus is different and is as someone said on a rolling development cycle. A static reference set just isn't in the cards for this core right now.

**Comment by Wilstorm** [comment] 2018-04-27 18:08
@SapphireTactician - At the expense of sounding condescending, I like that attitude. For a while there I thought we were going to break out the white gloves and start slapping each other across the face while claiming "How dare you good sir!" 

No honestly I thought it was a very reasonable and tame discussion and I always get something out of damn near every discussion. I love Bubble Bobble now...today...forever...for all eternity...this discussion will always be there for the rest of my days when I play Bubble Bobble like how peanut butter is to jelly or chocolate is to peanut butter or Tina is to Ike (wait, what?)

I do put programmers on a pedestal but that's what I went to school for when dinosaurs roamed the earth and I have a huge amount of respect for that type of talent. They probably have a few extra "votes" on what gets implemented first in context to the importance hierarchy though.

**Comment by SapphireTactician** [comment] 2018-04-27 18:46
Doesn't sound condescending at all. I'm glad I can say something that somebody's happy with today. Lol.

My older brother was the programmer is the family. I was his guinea pig from a young age, (*I always had a knack for making things break*) which was how I got into testing. I tried learning programming but I'm a very hasty and impatient person, so needless to say, I learned that programming wasn't for me. I abandoned it after learning it's take years before seeing any meaningful return on the time investment.

Eventually I felt like I found my calling in Quality Assurance; testing builds, reporting bugs and suggesting features and solutions. Which is eventually how I ended up here. I got a bit defensive because a lot of the places I contributed to in the past often had the mentality of "lowly testers have no say in the project" and I felt that vibe here earlier.

**Comment by arcadez** [comment] 2018-04-27 18:56
Well it got slightly heated in here as can happen in any debate where there are opposing viewpoints :)
the reason i decided to keep things current is any search for bublbobl.zip will only net you the
parent we're using here and the old parent is now a clone called bublbob1.zip.

Infact some of the clones have since been renamed once again and i felt for the average joe
not totally versed in the ways of roms who searches for bublbobl.zip has a higher likelyhood
of finding the correct version as the parent in this core is still the parent in currant MAME.

Thats it otherwise i would have kept the ole parent rom

**Comment by SapphireTactician** [comment] 2018-04-27 19:25
@arcadez That's very nice of you. I appreciate it. I'm sorry for giving you a headache over this. One question, if I want the mode select, which is why I went with `bublbobr` what would I need to do? I'll be willing to try and use a native Linux rom utility (*which I think Grant says exists*) if someone can walk me through it.

**Comment by arcadez** [comment] 2018-04-27 19:31
bubblbobr.zip as you know is a clone it will take all the roms from the parent set bublbobl.zip
the only unique roms it needs per say is the two main CPU dumps which you'll already have
in your set.

Basically by using the parent i just sent ya the mode select version should work across both cores
lemmie know if it doesn't and i'll help you further.

**Comment by SapphireTactician** [comment] 2018-04-27 19:39
I get it, yeah, that works. I was trying to keep every game non-merged so that the clone would work as a standalone zip but this is fine too. Should I close this issue now? @arcadez

**Closed** 2018-04-27 19:40 UTC

**Comment by markwkidd** [comment] 2018-04-27 19:42
@SapphireTactician you can 'un-merge' it yourself by copying the contents of the parent rom into the child rom zip.

But at this point you might want to be using a romset rebuilder tool to automate everything, thus the other issue. Thank you for keeping on with us here!

**Comment by SapphireTactician** [comment] 2018-04-27 19:45
Perhaps it should be I thanking you guys for not kicking me out. lol. I want to help but sometimes I worry if I'm being more of a pain when things like this happen.

**Comment by Wilstorm** [comment] 2018-04-27 20:26
Yeah I think it takes a specific type of person to be a programmer and some come by it naturally and the returns are immediate. It takes several skill sets to be good at it. 

If it's any consolation you create one heck of a through bug report! ;)

**Comment by Wilstorm** [comment] 2018-04-27 20:32
Thanks Arcadez. I do like the mode select though I doubt I will ever see level 100 to see the Easter Eggs of that game. It's pretty straight forward left or right joystick to pick the mode.
